<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AvsCurrentTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RootNamespace>Avalonia.Projection.Generator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Avalonia.Projection.Ir\Avalonia.Projection.Ir.csproj" />
  </ItemGroup>
</Project>
