<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AvsCurrentTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <Import Project="..\..\build\NullableEnable.props" />
  <Import Project="..\..\build\TrimmingEnable.props" />
</Project>
