<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(AvsCurrentTargetFramework)</TargetFramework>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\avalonia-src\packages\Avalonia\Avalonia.csproj" />
    <ProjectReference Include="..\..\interop\Avalonia.Rust\Avalonia.Rust.csproj" />
    <ProjectReference Include="..\..\interop\Avalonia.Rust.Interop\Avalonia.Rust.Interop.csproj" />
  </ItemGroup>
  <Import Project="..\..\build\NullableEnable.props" />
  <Import Project="..\..\build\BuildTargets.targets" />
</Project>
