use crate::geometry;
use crate::ir::{ProjectedEvent, ProjectedProperty, ProjectedType, ProjectionIr};

pub(crate) fn emit_safe_module(ir: &ProjectionIr) -> String {
    let mut out = String::from(
        "//! Generated by avalonia-bindgen. Do not edit.\n\
         #![allow(dead_code)]\n\n\
         use avalonia_sys as sys;\n\
         use crate::{runtime::{with_factory, AsControl, EventSubscription}, Result};\n\n",
    );
    out.push_str(&geometry::emit_safe_structs());
    if ir
        .types
        .iter()
        .any(|t| t.properties.iter().any(|p| p.kind == "DataTemplate"))
    {
        out.push_str(
            "/// A data template handed to an item-content property: Rust owns Match and\n\
             /// Build through the `avalonia_sys::data_template` CCW.\n\
             #[derive(Clone, Debug)]\n\
             pub struct DataTemplate {\n\
             \x20   pub(crate) raw: sys::ComPtr<sys::IAvnDataTemplate>,\n\
             }\n\n\
             impl DataTemplate {\n\
             \x20   pub(crate) fn from_raw(raw: sys::ComPtr<sys::IAvnDataTemplate>) -> Self {\n\
             \x20       Self { raw }\n\
             \x20   }\n\
             }\n\n",
        );
    }
    out.push_str(
        "/// Safe mirror of `Avalonia.PixelPoint`, marshalled as `sys::AvnPixelPoint`.\n\
         #[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n\
         pub struct PixelPoint {\n\
         \x20   pub x: i32,\n\
         \x20   pub y: i32,\n\
         }\n\n\
         impl PixelPoint {\n\
         \x20   pub const fn new(x: i32, y: i32) -> Self {\n\
         \x20       Self { x, y }\n\
         \x20   }\n\
         \x20   pub(crate) fn from_abi(value: sys::AvnPixelPoint) -> Self {\n\
         \x20       Self { x: value.x, y: value.y }\n\
         \x20   }\n\
         \x20   pub(crate) fn to_abi(self) -> sys::AvnPixelPoint {\n\
         \x20       sys::AvnPixelPoint { x: self.x, y: self.y }\n\
         \x20   }\n\
         }\n\n",
    );
    if ir
        .types
        .iter()
        .any(|t| t.properties.iter().any(|p| p.kind == "Variant"))
    {
        out.push_str(&crate::variant::emit_safe_enum());
    }
    if ir.brush_interface_name.is_some() {
        out.push_str(&emit_brush());
    }

    let flags_enums: std::collections::HashSet<&str> = ir
        .enums
        .iter()
        .filter(|projected_enum| projected_enum.is_flags)
        .map(|projected_enum| projected_enum.full_name.as_str())
        .collect();
    for projected_enum in &ir.enums {
        let mut values = Vec::new();
        for value in &projected_enum.values {
            if !values
                .iter()
                .any(|existing: &&crate::ir::ProjectedEnumValue| existing.value == value.value)
            {
                values.push(value);
            }
        }
        if projected_enum.is_flags {
            out.push_str(&format!(
                "/// [Flags] ABI bits for `{}`. Combined values are valid.\n",
                projected_enum.name
            ));
            out.push_str(&format!("pub mod {} {{\n", to_snake(&projected_enum.name)));
            for value in &values {
                out.push_str(&format!(
                    "    pub const {}: i32 = {};\n",
                    value.name.to_ascii_uppercase(),
                    value.value
                ));
            }
            out.push_str("}\n\n");
            continue;
        }
        out.push_str("#[repr(i32)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\n");
        out.push_str(&format!("pub enum {} {{\n", projected_enum.name));
        for value in &values {
            out.push_str(&format!("    {} = {},\n", value.name, value.value));
        }
        out.push_str("}\n\n");
        out.push_str(&format!(
            "impl TryFrom<i32> for {} {{\n\
             \x20   type Error = crate::Error;\n\
             \x20   fn try_from(value: i32) -> Result<Self> {{\n\
             \x20       match value {{\n",
            projected_enum.name
        ));
        for value in &values {
            out.push_str(&format!(
                "            {} => Ok(Self::{}),\n",
                value.value, value.name
            ));
        }
        out.push_str(
            "            _ => Err(crate::Error::InvalidEnumValue(value)),\n        }\n    }\n}\n\n",
        );
    }

    let mut event_argument_types = Vec::new();
    for event in ir.types.iter().flat_map(|ty| ty.events.iter()) {
        if event.payload_kind == "Args" {
            let name = simple_name(
                event
                    .args_interface_name
                    .as_deref()
                    .expect("argsInterfaceName"),
            )
            .to_string();
            if !event_argument_types.contains(&name) {
                out.push_str(&format!("pub use sys::{name};\n"));
                event_argument_types.push(name);
            }
        } else if !event.parameters.is_empty() {
            let name = event_arguments_name(event);
            if !event_argument_types.contains(&name) {
                out.push_str(&format!("pub use sys::{name};\n"));
                event_argument_types.push(name);
            }
        }
    }
    if !event_argument_types.is_empty() {
        out.push('\n');
    }

    for collection in unique_collections(ir) {
        out.push_str(&emit_collection(collection));
        out.push('\n');
    }

    for ty in ir.types.iter().filter(|ty| ty.kind == "Class") {
        out.push_str(&emit_type(ir, ty, &flags_enums));
        out.push('\n');
    }
    out.truncate(out.trim_end().len());
    out.push('\n');
    out
}

fn emit_brush() -> String {
    String::from(
        "/// A solid colour brush: the only brush shape that crosses the ABI.\n\
         ///\n\
         /// `Background`, `BorderBrush` and `Foreground` are carried as a colour plus an\n\
         /// opacity. Gradient, drawing and visual brushes are not projected; reading one back\n\
         /// from a control fails instead of degrading to a nearest colour.\n\
         #[derive(Clone, Copy, Debug, PartialEq)]\n\
         pub struct Brush {\n\
         \x20   pub color: Color,\n\
         \x20   pub opacity: f64,\n\
         }\n\n\
         impl Brush {\n\
         \x20   /// A fully opaque solid colour.\n\
         \x20   pub const fn solid(color: Color) -> Self {\n\
         \x20       Self {\n\
         \x20           color,\n\
         \x20           opacity: 1.0,\n\
         \x20       }\n\
         \x20   }\n\n\
         \x20   /// A solid colour drawn at `opacity`, where 1.0 is fully opaque.\n\
         \x20   pub const fn new(color: Color, opacity: f64) -> Self {\n\
         \x20       Self { color, opacity }\n\
         \x20   }\n\n\
         \x20   pub(crate) fn to_raw(self) -> Result<sys::ComPtr<sys::IAvnBrush>> {\n\
         \x20       with_factory(|factory| {\n\
         \x20           factory.create_solid_color_brush(self.color.into(), self.opacity)\n\
         \x20       })\n\
         \x20   }\n\n\
         \x20   pub(crate) fn from_raw(raw: &sys::ComPtr<sys::IAvnBrush>) -> Result<Self> {\n\
         \x20       Ok(Self {\n\
         \x20           color: raw.color()?.into(),\n\
         \x20           opacity: raw.opacity()?,\n\
         \x20       })\n\
         \x20   }\n\
         }\n\n\
         impl From<Color> for Brush {\n\
         \x20   fn from(color: Color) -> Self {\n\
         \x20       Self::solid(color)\n\
         \x20   }\n\
         }\n\n",
    )
}

fn emit_collection(property: &ProjectedProperty) -> String {
    let name = simple_name(property.interface_name.as_deref().expect("interfaceName"));
    let safe_name = name.strip_prefix("IAvn").unwrap_or(name);
    let mut out = format!(
        "#[derive(Clone, Debug)]\n\
         pub struct {safe_name} {{\n\
         \x20   pub(crate) raw: sys::ComPtr<sys::{name}>,\n\
         }}\n\n"
    );
    out.push_str(&format!(
        "impl {safe_name} {{\n\
         \x20   pub fn len(&self) -> Result<usize> {{ Ok(self.raw.len()?) }}\n\
         \x20   pub fn is_empty(&self) -> Result<bool> {{ Ok(self.len()? == 0) }}\n"
    ));
    match property.element_kind.as_deref() {
        Some("ComInterface") => {
            let element = simple_name(
                property
                    .element_interface_name
                    .as_deref()
                    .expect("elementInterfaceName"),
            )
            .strip_prefix("IAvn")
            .unwrap();
            out.push_str(&format!(
                "    pub fn get(&self, index: usize) -> Result<{element}> {{\n\
                 \x20       Ok({element} {{ raw: self.raw.get(index)? }})\n\
                 \x20   }}\n\
                 \x20   pub fn add(&self, value: impl As{element}) -> Result<()> {{\n\
                 \x20       let value = value.as_{element_snake}()?;\n\
                 \x20       Ok(self.raw.add(&value)?)\n\
                 \x20   }}\n",
                element_snake = to_snake(element)
            ));
        }
        Some("StringUtf16") => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<String> {\n\
             \x20       unsafe { sys::take_utf16(self.raw.get(index)?).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: impl AsRef<str>) -> Result<()> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       Ok(self.raw.add(&value)?)\n\
             \x20   }\n\
             \x20   pub fn contains(&self, value: impl AsRef<str>) -> Result<bool> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       Ok(self.raw.index_of(&value)?.is_some())\n\
             \x20   }\n\
             \x20   pub fn remove_value(&self, value: impl AsRef<str>) -> Result<bool> {\n\
             \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
             \x20       if let Some(index) = self.raw.index_of(&value)? {\n\
             \x20           self.raw.remove(index)?;\n\
             \x20           Ok(true)\n\
             \x20       } else {\n\
             \x20           Ok(false)\n\
             \x20       }\n\
             \x20   }\n",
        ),
        Some("Variant") => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<Variant> {\n\
             \x20       Ok(Variant::from_abi(self.raw.get(index)?))\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: impl Into<Variant>) -> Result<()> {\n\
             \x20       let value = value.into().to_abi()?;\n\
             \x20       Ok(self.raw.add(*value)?)\n\
             \x20   }\n\
             \x20   pub fn contains(&self, value: impl Into<Variant>) -> Result<bool> {\n\
             \x20       let value = value.into().to_abi()?;\n\
             \x20       Ok(self.raw.index_of(*value)?.is_some())\n\
             \x20   }\n",
        ),
        Some("DateTimeI64") => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<std::time::SystemTime> {\n\
             \x20       let ticks = self.raw.get(index)?;\n\
             \x20       let unix_ticks = ticks - sys::DOTNET_EPOCH_OFFSET_TICKS;\n\
             \x20       let nanos = (unix_ticks.clamp(0, i64::MAX) as u128) * 100;\n\
             \x20       Ok(std::time::UNIX_EPOCH + std::time::Duration::from_nanos(nanos as u64))\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: std::time::SystemTime) -> Result<()> {\n\
             \x20       let ticks = value\n\
             \x20           .duration_since(std::time::UNIX_EPOCH)\n\
             \x20           .map(|delta| delta.as_nanos() / 100)\n\
             \x20           .unwrap_or(0) as i64;\n\
             \x20       Ok(self.raw.add(ticks + sys::DOTNET_EPOCH_OFFSET_TICKS)?)\n\
             \x20   }\n\
             \x20   pub fn contains(&self, value: std::time::SystemTime) -> Result<bool> {\n\
             \x20       let ticks = value\n\
             \x20           .duration_since(std::time::UNIX_EPOCH)\n\
             \x20           .map(|delta| delta.as_nanos() / 100)\n\
             \x20           .unwrap_or(0) as i64;\n\
             \x20       Ok(self.raw.index_of(ticks + sys::DOTNET_EPOCH_OFFSET_TICKS)?.is_some())\n\
             \x20   }\n",
        ),
        kind => panic!("unsupported safe collection element kind {kind:?}"),
    }
    out.push_str(
        "    pub fn remove(&self, index: usize) -> Result<()> { Ok(self.raw.remove(index)?) }\n\
         \x20   pub fn clear(&self) -> Result<()> { Ok(self.raw.clear()?) }\n\
         }\n",
    );
    out
}

fn emit_type(
    ir: &ProjectionIr,
    ty: &ProjectedType,
    flags_enums: &std::collections::HashSet<&str>,
) -> String {
    let safe_name = interface_suffix(&ty.name);
    let mut out = format!(
        "#[derive(Clone, Debug)]\n\
         pub struct {safe_name} {{\n\
         \x20   pub(crate) raw: sys::ComPtr<sys::{interface_name}>,\n\
         }}\n\n\
         impl {safe_name} {{\n",
        interface_name = ty.name
    );

    if ty.is_constructible {
        out.push_str(&format!(
            "    pub fn new() -> Result<Self> {{\n\
             \x20       with_factory(|factory| factory.create_{factory_name}())\n\
             \x20           .map(|raw| Self {{ raw }})\n\
             \x20   }}\n",
            factory_name = to_snake(safe_name)
        ));
    }

    let reserved_methods: std::collections::HashSet<String> = lineage(ir, ty)
        .iter()
        .flat_map(|owner| owner.methods.iter().map(|method| to_snake(&method.name)))
        .collect();
    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            out.push_str(&emit_property(property, &reserved_methods, flags_enums));
            if property.kind == "ComCollection" && property.name == "Children" {
                out.push_str(
                    "    pub fn child(self, value: impl AsControl) -> Result<Self> {\n\
                     \x20       self.children()?.add(value)?;\n\
                     \x20       Ok(self)\n\
                     \x20   }\n",
                );
            }
            if property.kind == "ComCollection" && property.name == "Items" {
                out.push_str(
                    "    pub fn item(self, value: impl AsControl) -> Result<Self> {\n\
                      \x20       self.items()?.add(value)?;\n\
                      \x20       Ok(self)\n\
                      \x20   }\n",
                );
            }
        }
        for method in &owner.methods {
            out.push_str(&emit_method(ty, method));
        }
        for event in &owner.events {
            out.push_str(&emit_event(event));
        }
    }
    for property in ir
        .attached_properties
        .iter()
        .filter(|property| property.owner_name == safe_name)
    {
        out.push_str(&emit_attached_property(property, ir));
    }
    out.push_str("}\n\n");

    if is_control(ir, ty) {
        out.push_str(&format!(
            "impl AsControl for {safe_name} {{\n\
             \x20   fn as_control(&self) -> Result<sys::ComPtr<sys::IAvnControl>> {{\n\
             \x20       Ok(self.raw.query_interface()?)\n\
             \x20   }}\n\
             }}\n"
        ));
    }

    fn emit_attached_property(
        property: &crate::ir::ProjectedAttachedProperty,
        ir: &ProjectionIr,
    ) -> String {
        let owner = to_snake(&property.owner_name);
        let name = to_snake(&property.name);
        if property.kind == "StringUtf16" {
            // A string attached property is owned by the caller after the get, so it is taken
            // rather than borrowed. A nullable one reports an absent value as None instead of
            // an empty string, because "no tip" and "empty tip" are different states.
            let (get_type, get_body) = if property.is_nullable {
                (
                    "Option<String>",
                    "        unsafe { Ok(sys::take_utf16(value)) }",
                )
            } else {
                (
                    "String",
                    "        unsafe { sys::take_utf16(value).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }",
                )
            };
            return format!(
                "    pub fn get_{name}(target: &impl AsControl) -> Result<{get_type}> {{\n\
                 \x20       let target = target.as_control()?;\n\
                 \x20       let value = with_factory(|factory| factory.get_{owner}_statics()?.get_{name}(&target))?;\n\
                 {get_body}\n\
                 \x20   }}\n\
                 \x20   pub fn set_{name}(target: &impl AsControl, value: impl AsRef<str>) -> Result<()> {{\n\
                 \x20       let target = target.as_control()?;\n\
                 \x20       let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n\
                 \x20       with_factory(|factory| factory.get_{owner}_statics()?.set_{name}(&target, &value))\n\
                 \x20   }}\n"
            );
        }
        let enum_name = simple_name(&property.managed_type_name);
        let is_enum = ir
            .enums
            .iter()
            .any(|projected_enum| projected_enum.full_name == property.managed_type_name);
        let safe_type = if is_enum {
            enum_name.to_string()
        } else if property.kind == "TimeSpanI64" {
            "std::time::Duration".to_string()
        } else if let Some(geometry) = geometry::find(&property.kind) {
            if property.is_nullable {
                format!("Option<{}>", geometry.safe_name)
            } else {
                geometry.safe_name.to_string()
            }
        } else {
            rust_scalar_kind(&property.kind).to_string()
        };
        let raw_get = if is_enum {
            format!("{enum_name}::try_from(value)")
        } else if property.kind == "TimeSpanI64" {
            "Ok(std::time::Duration::from_nanos(value.clamp(0, i64::MAX / 100) as u64 * 100))"
                .to_string()
        } else if let Some(geometry) = geometry::find(&property.kind) {
            if property.is_nullable {
                format!("Ok({}::from_optional_abi(value))", geometry.safe_name)
            } else {
                "Ok(value.into())".to_string()
            }
        } else {
            "Ok(value)".to_string()
        };
        let raw_set = if is_enum {
            "value as i32".to_string()
        } else if property.kind == "TimeSpanI64" {
            "(value.as_nanos() / 100).clamp(0, i64::MAX as u128) as i64".to_string()
        } else if let Some(geometry) = geometry::find(&property.kind) {
            if property.is_nullable {
                format!("{}::to_optional_abi(value)", geometry.safe_name)
            } else {
                "value.into()".to_string()
            }
        } else {
            "value".to_string()
        };
        format!(
            "    pub fn get_{name}(target: &impl AsControl) -> Result<{safe_type}> {{\n\
             \x20       let target = target.as_control()?;\n\
             \x20       let value = with_factory(|factory| factory.get_{owner}_statics()?.get_{name}(&target))?;\n\
             \x20       {raw_get}\n\
             \x20   }}\n\
             \x20   pub fn set_{name}(target: &impl AsControl, value: {safe_type}) -> Result<()> {{\n\
             \x20       let target = target.as_control()?;\n\
             \x20       with_factory(|factory| factory.get_{owner}_statics()?.set_{name}(&target, {raw_set}))\n\
             \x20   }}\n"
        )
    }
    out
}

fn emit_property(
    property: &ProjectedProperty,
    reserved_methods: &std::collections::HashSet<String>,
    flags_enums: &std::collections::HashSet<&str>,
) -> String {
    let snake = to_snake(&property.name);
    let getter = if property.can_write {
        format!("get_{snake}")
    } else {
        snake.clone()
    };
    // Bool builders drop the `is_` prefix (`IsEnabled` → `enabled`) unless that
    // collides with a method on the same type (`IsOpen` vs `Open()`).
    let builder = if property.kind == "Bool" || property.kind == "NullableBool" {
        match snake.strip_prefix("is_") {
            Some(stripped) if !reserved_methods.contains(stripped) => stripped,
            _ => snake.as_str(),
        }
    } else {
        snake.as_str()
    };
    let mut out = String::new();

    if property.can_read {
        match property.kind.as_str() {
            "StringUtf16" if property.is_nullable => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Option<String>> {{\n\
                 \x20       unsafe {{ Ok(sys::take_utf16(self.raw.get_{snake}()?)) }}\n\
                 \x20   }}\n"
            )),
            "StringUtf16" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<String> {{\n\
                 \x20       unsafe {{ sys::take_utf16(self.raw.get_{snake}()?).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }}\n\
                 \x20   }}\n"
            )),
            "ComInterface" => {
                let safe_type = interface_suffix(simple_name(
                    property.interface_name.as_deref().expect("interfaceName"),
                ));
                if property.is_nullable {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<Option<{safe_type}>> {{\n\
                         \x20       Ok(self.raw.get_{snake}()?.map(|raw| {safe_type} {{ raw }}))\n\
                         \x20   }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<{safe_type}> {{\n\
                         \x20       Ok({safe_type} {{ raw: self.raw.get_{snake}()? }})\n\
                         \x20   }}\n"
                    ));
                }
            }
            "ComCollection" => {
                let safe_type = interface_suffix(simple_name(
                    property.interface_name.as_deref().expect("interfaceName"),
                ));
                if property.is_nullable {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<Option<{safe_type}>> {{\n\
                         \x20       Ok(self.raw.get_{snake}()?.map(|raw| {safe_type} {{ raw }}))\n\
                         \x20   }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<{safe_type}> {{\n\
                         \x20       Ok({safe_type} {{ raw: self.raw.get_{snake}()? }})\n\
                         \x20   }}\n"
                    ));
                }
            }
            "Brush" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Option<Brush>> {{\n\
                 \x20       self.raw.get_{snake}()?.as_ref().map(Brush::from_raw).transpose()\n\
                 \x20   }}\n"
            )),
            "Command" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Option<sys::ComPtr<sys::IAvnCommand>>> {{\n\
                 \x20       Ok(self.raw.get_{snake}()?)\n\
                 \x20   }}\n"
            )),
            "DataTemplate" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Option<DataTemplate>> {{\n\
                 \x20       Ok(self.raw.get_{snake}()?.map(|raw| DataTemplate {{ raw }}))\n\
                 \x20   }}\n"
            )),
            "ItemFilter" | "TextFilter" | "ItemSelector" | "TextSelector" | "PopupPlacement"
            | "AsyncPopulator" => {
                let full = simple_name(
                    property.interface_name.as_deref().expect("interfaceName"),
                );
                out.push_str(&format!(
                    "    pub fn {getter}(&self) -> Result<Option<sys::ComPtr<sys::{full}>>> {{\n\
                     \x20       Ok(self.raw.get_{snake}()?)\n\
                     \x20   }}\n"
                ));
            }
            "Variant" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<Variant> {{\n\
                 \x20       Ok(Variant::from_abi(self.raw.get_{snake}()?))\n\
                 \x20   }}\n"
            )),
            "TimeSpanI64" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<std::time::Duration> {{\n\
                 \x20       let ticks = self.raw.get_{snake}()?;\n\
                 \x20       Ok(std::time::Duration::from_nanos(ticks.clamp(0, i64::MAX / 100) as u64 * 100))\n\
                 \x20   }}\n"
            )),
            "PixelPointI32" => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<PixelPoint> {{\n\
                 \x20       Ok(PixelPoint::from_abi(self.raw.get_{snake}()?))\n\
                 \x20   }}\n"
            )),
            "I32" if is_enum_property(property, flags_enums) => {
                let enum_name = simple_name(property.managed_type_name.as_deref().unwrap());
                out.push_str(&format!(
                    "    pub fn {getter}(&self) -> Result<{enum_name}> {{\n\
                     \x20       let value = self.raw.get_{snake}()?;\n\
                     \x20       {enum_name}::try_from(value)\n\
                     \x20   }}\n"
                ));
            }
            kind if geometry::is_geometry(kind) => {
                let safe_type = geometry::find(kind).unwrap().safe_name;
                if property.is_nullable {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<Option<{safe_type}>> {{\n\
                         \x20       Ok({safe_type}::from_optional_abi(self.raw.get_{snake}()?))\n\
                         \x20   }}\n"
                    ));
                } else {
                    out.push_str(&format!(
                        "    pub fn {getter}(&self) -> Result<{safe_type}> {{\n\
                         \x20       Ok(self.raw.get_{snake}()?.into())\n\
                         \x20   }}\n"
                    ));
                }
            }
            _ => out.push_str(&format!(
                "    pub fn {getter}(&self) -> Result<{}> {{ Ok(self.raw.get_{snake}()?) }}\n",
                safe_scalar_type(property, flags_enums)
            )),
        }
    }

    if property.can_write {
        let (argument, setup, value) = safe_property_input(property, flags_enums);
        out.push_str(&format!(
            "    pub fn set_{builder}(&self, value: {argument}) -> Result<()> {{\n{setup}        Ok(self.raw.set_{snake}({value})?)\n    }}\n\
             \x20   pub fn {builder}(self, value: {argument}) -> Result<Self> {{\n\
             \x20       self.set_{builder}(value)?;\n\
             \x20       Ok(self)\n\
             \x20   }}\n"
        ));
    }
    out
}

fn emit_event(event: &ProjectedEvent) -> String {
    if event.payload_kind == "Args" {
        // The callback receives the args interface wrapper with count/getter methods.
        let event_name = to_snake(&event.name);
        let args_name = simple_name(
            event
                .args_interface_name
                .as_deref()
                .expect("argsInterfaceName"),
        );
        let handler_name = simple_name(&event.handler_interface_name)
            .strip_prefix("IAvn")
            .unwrap_or_else(|| simple_name(&event.handler_interface_name))
            .strip_suffix("Handler")
            .unwrap_or_else(|| simple_name(&event.handler_interface_name));
        let handler_function = format!("{}_handler", to_snake(handler_name));
        return format!(
            "    pub fn subscribe_{event_name}(&self, callback: impl FnMut(&mut sys::ComPtr<sys::{args_name}>) + Send + 'static) -> Result<EventSubscription> {{\n\
             \x20       let mut callback = callback;\n\
             \x20       let handler = sys::{handler_function}(move |args| {{ callback(args); Ok(()) }});\n\
             \x20       let subscription_id = self.raw.advise_{event_name}(&handler)?;\n\
             \x20       let source = self.raw.clone();\n\
             \x20       Ok(EventSubscription::new(move || source.unadvise_{event_name}(subscription_id)))\n\
             \x20   }}\n\
             \x20   pub fn on_{event_name}(self, scope: &crate::AppScope, callback: impl FnMut(&mut sys::ComPtr<sys::{args_name}>) + Send + 'static) -> Result<Self> {{\n\
              \x20       scope.retain_subscription(self.subscribe_{event_name}(callback)?);\n\
              \x20       Ok(self)\n\
              \x20   }}\n"
        );
    }
    if !event.parameters.is_empty() {
        let event_name = to_snake(&event.name);
        let args_name = event_arguments_name(event);
        let handler_name = simple_name(&event.handler_interface_name)
            .strip_prefix("IAvn")
            .unwrap_or_else(|| simple_name(&event.handler_interface_name))
            .strip_suffix("Handler")
            .unwrap_or_else(|| simple_name(&event.handler_interface_name));
        let handler_function = format!("{}_handler", to_snake(handler_name));
        return format!(
            "    pub fn subscribe_{event_name}(&self, callback: impl FnMut(&mut {args_name}) + Send + 'static) -> Result<EventSubscription> {{\n\
             \x20       let mut callback = callback;\n\
             \x20       let handler = sys::{handler_function}(move |event| {{ callback(event); Ok(()) }});\n\
             \x20       let subscription_id = self.raw.advise_{event_name}(&handler)?;\n\
             \x20       let source = self.raw.clone();\n\
             \x20       Ok(EventSubscription::new(move || source.unadvise_{event_name}(subscription_id)))\n\
             \x20   }}\n\
             \x20   pub fn on_{event_name}(self, scope: &crate::AppScope, callback: impl FnMut(&mut {args_name}) + Send + 'static) -> Result<Self> {{\n\
              \x20       scope.retain_subscription(self.subscribe_{event_name}(callback)?);\n\
             \x20       Ok(self)\n\
             \x20   }}\n"
        );
    }
    assert_eq!(event.payload_kind, "None", "unsupported event payload kind");
    let event_name = to_snake(&event.name);
    let handler_name = simple_name(&event.handler_interface_name)
        .strip_prefix("IAvn")
        .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        .strip_suffix("Handler")
        .unwrap_or_else(|| {
            simple_name(&event.handler_interface_name)
                .strip_prefix("IAvn")
                .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        });
    let handler_function = format!("{}_handler", to_snake(handler_name));
    format!(
        "    pub fn subscribe_{event_name}(&self, mut callback: impl FnMut(()) + Send + 'static) -> Result<EventSubscription> {{\n\
         \x20       let handler = sys::{handler_function}(move || {{\n\
         \x20           callback(());\n\
         \x20           Ok(())\n\
         \x20       }});\n\
         \x20       let subscription_id = self.raw.advise_{event_name}(&handler)?;\n\
         \x20       let source = self.raw.clone();\n\
         \x20       Ok(EventSubscription::new(move || source.unadvise_{event_name}(subscription_id)))\n\
         \x20   }}\n\
         \x20   pub fn on_{event_name}(self, scope: &crate::AppScope, callback: impl FnMut(()) + Send + 'static) -> Result<Self> {{\n\
         \x20       scope.retain_subscription(self.subscribe_{event_name}(callback)?);\n\
         \x20       Ok(self)\n\
         \x20   }}\n"
    )
}

fn event_arguments_name(event: &ProjectedEvent) -> String {
    let handler = simple_name(&event.handler_interface_name);
    format!(
        "{}EventArgs",
        handler
            .strip_prefix("IAvn")
            .unwrap_or(handler)
            .strip_suffix("Handler")
            .unwrap_or(handler)
    )
}

fn emit_method(ty: &ProjectedType, method: &crate::ir::ProjectedMethod) -> String {
    let name = to_snake(&method.name);
    if ty.name == "IAvnWindow" && method.name == "Show" {
        return String::new();
    }
    // A parameter typed as the root control interface accepts any projected control, the same
    // way a control-valued property setter does. Anything more specific stays concrete, so
    // `TreeView::expand_sub_tree` still demands a `TreeViewItem` rather than any control.
    let is_any_control = |parameter: &crate::ir::ProjectedParameter| {
        parameter.kind == "ComInterface"
            && parameter
                .interface_name
                .as_deref()
                .map(simple_name)
                .map(interface_suffix)
                == Some("Control")
    };
    let ins: Vec<_> = method
        .parameters
        .iter()
        .filter(|parameter| parameter.direction != "Out")
        .collect();
    let outs: Vec<_> = method
        .parameters
        .iter()
        .filter(|parameter| parameter.direction == "Out")
        .collect();
    let arguments = ins
        .iter()
        .map(|parameter| {
            let parameter_name = to_snake(&parameter.name);
            if is_any_control(parameter) {
                if parameter.is_nullable {
                    format!("{parameter_name}: Option<&impl AsControl>")
                } else {
                    format!("{parameter_name}: &impl AsControl")
                }
            } else if parameter.kind == "ComInterface" {
                let safe = interface_suffix(simple_name(
                    parameter.interface_name.as_deref().expect("interfaceName"),
                ));
                if parameter.is_nullable {
                    format!("{parameter_name}: Option<&{safe}>")
                } else {
                    format!("{parameter_name}: &{safe}")
                }
            } else if parameter.kind == "Notification" {
                let full = simple_name(parameter.interface_name.as_deref().expect("interfaceName"));
                if parameter.is_nullable {
                    format!("{parameter_name}: Option<&sys::ComPtr<sys::{full}>>")
                } else {
                    format!("{parameter_name}: &sys::ComPtr<sys::{full}>")
                }
            } else if parameter.kind == "Variant" {
                format!("{parameter_name}: impl Into<Variant>")
            } else if parameter.kind == "StringUtf16" {
                if parameter.is_nullable {
                    format!("{parameter_name}: Option<&str>")
                } else {
                    format!("{parameter_name}: impl AsRef<str>")
                }
            } else if let Some(geometry) = geometry::find(&parameter.kind) {
                format!("{parameter_name}: {}", geometry.safe_name)
            } else {
                format!("{parameter_name}: {}", rust_scalar_kind(&parameter.kind))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let setup = ins
        .iter()
        .filter(|parameter| is_any_control(parameter) || parameter.kind == "StringUtf16")
        .map(|parameter| {
            let parameter_name = to_snake(&parameter.name);
            if parameter.kind == "StringUtf16" {
                if parameter.is_nullable {
                    format!("        let {parameter_name}: Option<Vec<u16>> = {parameter_name}.map(|value| value.encode_utf16().chain(Some(0)).collect());\n")
                } else {
                    format!("        let {parameter_name}: Vec<u16> = {parameter_name}.as_ref().encode_utf16().chain(Some(0)).collect();\n")
                }
            } else if parameter.is_nullable {
                format!(
                    "        let {parameter_name} = {parameter_name}.map(|value| value.as_control()).transpose()?;\n"
                )
            } else {
                format!("        let {parameter_name} = {parameter_name}.as_control()?;\n")
            }
        })
        .collect::<String>();
    let call_arguments = ins
        .iter()
        .map(|parameter| {
            let parameter_name = to_snake(&parameter.name);
            if is_any_control(parameter) {
                if parameter.is_nullable {
                    format!("{parameter_name}.as_ref()")
                } else {
                    format!("&{parameter_name}")
                }
            } else if parameter.kind == "ComInterface" {
                if parameter.is_nullable {
                    format!("{parameter_name}.map(|value| &value.raw)")
                } else {
                    format!("&{parameter_name}.raw")
                }
            } else if parameter.kind == "Notification" {
                format!("{parameter_name}")
            } else if parameter.kind == "StringUtf16" {
                if parameter.is_nullable {
                    format!("{parameter_name}.as_deref()")
                } else {
                    format!("&{parameter_name}")
                }
            } else if parameter.kind == "Variant" {
                format!("*{parameter_name}.into().to_abi()?")
            } else if geometry::is_geometry(&parameter.kind) {
                format!("{parameter_name}.into()")
            } else {
                parameter_name
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    let separator = if arguments.is_empty() { "" } else { ", " };
    let (result_type, result_expr): (String, String) = match outs.as_slice() {
        [] => (
            "()".into(),
            format!("Ok(self.raw.{name}({call_arguments})?)"),
        ),
        [output] if output.kind == "Bool" => (
            "bool".into(),
            format!("Ok(self.raw.{name}({call_arguments})? != 0)"),
        ),
        [output] if output.kind == "StringUtf16" => (
            "String".into(),
            format!("unsafe {{ sys::take_utf16(self.raw.{name}({call_arguments})?).ok_or(crate::Error::Abi(sys::Error(sys::E_POINTER))) }}"),
        ),
        [output] if output.kind == "Variant" => (
            "Variant".into(),
            format!("Ok(Variant::from_abi(self.raw.{name}({call_arguments})?))"),
        ),
        [output] if output.kind == "ComInterface" => {
            let safe = interface_suffix(simple_name(
                output.interface_name.as_deref().expect("interfaceName"),
            ));
            if output.is_nullable {
                (
                    format!("Option<{safe}>"),
                    format!(
                        "Ok(self.raw.{name}({call_arguments})?.map(|raw| {safe} {{ raw }}))"
                    ),
                )
            } else {
                (
                    safe.to_string(),
                    format!("Ok({safe} {{ raw: self.raw.{name}({call_arguments})? }})"),
                )
            }
        }
        [output] => (
            rust_scalar_kind(&output.kind).into(),
            format!("Ok(self.raw.{name}({call_arguments})?)"),
        ),
        _ => ("()".into(), format!("Ok(self.raw.{name}({call_arguments})?)")),
    };
    if setup.is_empty() && !result_expr.contains('\n') {
        return format!(
            "    pub fn {name}(&self{separator}{arguments}) -> Result<{result_type}> {{ {result_expr} }}\n"
        );
    }
    format!(
        "    pub fn {name}(&self{separator}{arguments}) -> Result<{result_type}> {{\n\
         {setup}        {result_expr}\n\
         \x20   }}\n"
    )
}

fn safe_property_input(
    property: &ProjectedProperty,
    flags_enums: &std::collections::HashSet<&str>,
) -> (String, String, String) {
    if let Some(geometry) = geometry::find(&property.kind) {
        if property.is_nullable {
            return (
                format!("Option<{}>", geometry.safe_name),
                String::new(),
                format!("{}::to_optional_abi(value)", geometry.safe_name),
            );
        }
        return (
            geometry.safe_name.into(),
            String::new(),
            "value.into()".into(),
        );
    }
    match property.kind.as_str() {
        "StringUtf16" => (
            "impl AsRef<str>".into(),
            "        let value: Vec<u16> = value.as_ref().encode_utf16().chain(Some(0)).collect();\n"
                .into(),
            if property.is_nullable {
                "Some(&value)".into()
            } else {
                "&value".into()
            },
        ),
        "ComInterface" => {
            let safe = interface_suffix(simple_name(
                property.interface_name.as_deref().expect("interfaceName"),
            ));
            if safe == "Control" {
                if property.is_nullable {
                    return (
                        "Option<&dyn AsControl>".into(),
                        "        let value = value.map(|value| value.as_control()).transpose()?;\n".into(),
                        "value.as_ref()".into(),
                    );
                }
                (
                    "impl AsControl".into(),
                    "        let value = value.as_control()?;\n".into(),
                    "&value".into(),
                )
            } else {
                if property.is_nullable {
                    return (
                        format!("Option<&{safe}>"),
                        String::new(),
                        "value.map(|value| &value.raw)".into(),
                    );
                }
                (
                    format!("&{safe}"),
                    String::new(),
                    "&value.raw".into(),
                )
            }
        }
        "ComCollection" => {
            let safe = interface_suffix(simple_name(
                property.interface_name.as_deref().expect("interfaceName"),
            ));
            if property.is_nullable {
                (
                    format!("Option<&{safe}>"),
                    String::new(),
                    "value.map(|value| &value.raw)".into(),
                )
            } else {
                (
                    format!("&{safe}"),
                    String::new(),
                    "&value.raw".into(),
                )
            }
        }
        "Brush" => (
            "impl Into<Option<Brush>>".into(),
            "        let value = value.into().map(Brush::to_raw).transpose()?;\n".into(),
            "value.as_ref()".into(),
        ),
        "Command" => (
            "Option<&sys::ComPtr<sys::IAvnCommand>>".into(),
            String::new(),
            "value".into(),
        ),
        "DataTemplate" => (
            "Option<&DataTemplate>".into(),
            String::new(),
            "value.map(|value| &value.raw)".into(),
        ),
        "ItemFilter" | "TextFilter" | "ItemSelector" | "TextSelector" | "PopupPlacement"
            | "AsyncPopulator" => {
            let full = simple_name(
                property.interface_name.as_deref().expect("interfaceName"),
            );
            (
                format!("Option<&sys::ComPtr<sys::{full}>>"),
                String::new(),
                "value".into(),
            )
        }
        "Variant" => (
            "impl Into<Variant>".into(),
            "        let value = value.into().to_abi()?;\n".into(),
            "&value".into(),
        ),
        "TimeSpanI64" => (
            "std::time::Duration".into(),
            "        let value = (value.as_nanos() / 100).clamp(0, i64::MAX as u128) as i64;\n".into(),
            "value".into(),
        ),
        "PixelPointI32" => (
            "PixelPoint".into(),
            "        let value = value.to_abi();\n".into(),
            "value".into(),
        ),
        "I32" if is_enum_property(property, flags_enums) => (
            simple_name(property.managed_type_name.as_deref().unwrap()).into(),
            String::new(),
            "value as i32".into(),
        ),
        _ => (
            safe_scalar_type(property, flags_enums),
            String::new(),
            "value".into(),
        ),
    }
}

fn safe_scalar_type(
    property: &ProjectedProperty,
    flags_enums: &std::collections::HashSet<&str>,
) -> String {
    if let Some(geometry) = geometry::find(&property.kind) {
        if property.is_nullable {
            format!("Option<{}>", geometry.safe_name)
        } else {
            geometry.safe_name.into()
        }
    } else if property.kind == "I32" && is_enum_property(property, flags_enums) {
        simple_name(property.managed_type_name.as_deref().unwrap()).into()
    } else {
        rust_scalar_kind(&property.kind).into()
    }
}

fn rust_scalar_kind(kind: &str) -> &str {
    match kind {
        "CharUtf16" => "u16",
        "I32" => "i32",
        "I64" => "i64",
        "TimeSpanI64" => "i64",
        "F32" => "f32",
        "F64" => "f64",
        "Bool" => "bool",
        "NullableBool" => "Option<bool>",
        _ => "()",
    }
}

fn is_enum_property(
    property: &ProjectedProperty,
    flags_enums: &std::collections::HashSet<&str>,
) -> bool {
    property.kind == "I32"
        && property.managed_type_name.as_deref() != Some("System.Int32")
        && !property
            .managed_type_name
            .as_deref()
            .is_some_and(|name| flags_enums.contains(name))
}

fn is_control(ir: &ProjectionIr, ty: &ProjectedType) -> bool {
    lineage(ir, ty)
        .iter()
        .any(|candidate| candidate.name == "IAvnControl")
}

fn lineage<'a>(ir: &'a ProjectionIr, ty: &'a ProjectedType) -> Vec<&'a ProjectedType> {
    let mut result = vec![ty];
    let mut current = ty;
    while let Some(base) = &current.base_full_name {
        current = ir
            .types
            .iter()
            .find(|candidate| &candidate.full_name == base)
            .expect("base type must be present in projection IR");
        result.push(current);
    }
    result.reverse();
    result
}

fn unique_collections(ir: &ProjectionIr) -> Vec<&ProjectedProperty> {
    let mut result = Vec::new();
    for property in ir
        .types
        .iter()
        .flat_map(|ty| ty.properties.iter())
        .filter(|property| property.kind == "ComCollection")
    {
        if !result
            .iter()
            .any(|existing: &&ProjectedProperty| existing.interface_name == property.interface_name)
        {
            result.push(property);
        }
    }
    result
}

fn interface_suffix(name: &str) -> &str {
    name.strip_prefix("IAvn").unwrap_or(name)
}

fn simple_name(full_name: &str) -> &str {
    full_name.rsplit('.').next().unwrap_or(full_name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, path::PathBuf, process::Command, time::SystemTime};

    #[test]
    fn safe_string_methods_and_interface_setters_compile_and_preserve_nulls() {
        let ty: ProjectedType = serde_json::from_value(serde_json::json!({
            "name": "IAvnFixture", "fullName": "Tests.IAvnFixture", "kind": "Class",
            "methods": [{
                "name": "WriteStrings", "returnKind": "I32", "preserveSig": true,
                "parameters": [
                    { "name": "required", "kind": "StringUtf16", "direction": "In" },
                    { "name": "optional", "kind": "StringUtf16", "direction": "In", "isNullable": true }
                ]
            }]
        }))
        .unwrap();
        let mut members = emit_method(&ty, &ty.methods[0]);
        for (name, interface, nullable) in [
            ("RequiredControl", "IAvnControl", false),
            ("OptionalControl", "IAvnControl", true),
            ("RequiredSpecific", "IAvnSpecific", false),
            ("OptionalSpecific", "IAvnSpecific", true),
        ] {
            let property: ProjectedProperty = serde_json::from_value(serde_json::json!({
                "name": name, "kind": "ComInterface", "interfaceName": interface,
                "canWrite": true, "isNullable": nullable
            }))
            .unwrap();
            members.push_str(&emit_property(
                &property,
                &Default::default(),
                &Default::default(),
            ));
        }
        let source = include_str!("../test-fixtures/safe_inputs.rs")
            .replace("// GENERATED_MEMBERS", &members);
        let stamp = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let directory = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("..")
            .join("target")
            .join(format!("bindgen-compile-{}-{stamp}", std::process::id()));
        fs::create_dir_all(&directory).unwrap();
        struct Cleanup(PathBuf);
        impl Drop for Cleanup {
            fn drop(&mut self) {
                let _ = fs::remove_dir_all(&self.0);
            }
        }
        let _cleanup = Cleanup(directory.clone());
        let source_path = directory.join("safe_inputs.rs");
        let executable = directory.join(format!("safe_inputs{}", std::env::consts::EXE_SUFFIX));
        fs::write(&source_path, source).unwrap();
        let compiled = Command::new("rustc")
            .args(["--edition=2021", "--crate-name", "safe_inputs"])
            .arg(&source_path)
            .arg("-o")
            .arg(&executable)
            .output()
            .unwrap();
        assert!(
            compiled.status.success(),
            "{}",
            String::from_utf8_lossy(&compiled.stderr)
        );
        let executed = Command::new(executable).output().unwrap();
        assert!(
            executed.status.success(),
            "{}",
            String::from_utf8_lossy(&executed.stderr)
        );
    }
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}
