use crate::geometry;
use crate::ir::{
    ProjectedAttachedProperty, ProjectedEvent, ProjectedMethod, ProjectedParameter,
    ProjectedProperty, ProjectedType, ProjectionIr,
};
use crate::variant;

pub(crate) fn emit_sys_module(ir: &ProjectionIr) -> String {
    let mut out = String::from(
        "//! Generated by avalonia-bindgen. Do not edit.\n\
         #![allow(dead_code, non_snake_case)]\n\n\
         use crate::com::{ComInterface, ComPtr, IUnknown};\n\
         use crate::guid::Guid;\n\
         use crate::hresult::{self, Error, Result};\n\
         use std::ffi::c_void;\n\
         use std::ptr;\n\n",
    );
    out.push_str(&geometry::emit_sys_structs());
    out.push_str(
        "/// Blittable ABI mirror of a nullable DateTime tick count.\n\
         #[repr(C)]\n\
         #[derive(Clone, Copy, Debug, Default, PartialEq)]\n\
         pub struct AvnOptionalDateTime {\n\
         \x20   pub has_value: i32,\n\
         \x20   pub ticks: i64,\n\
         }\n\n\
         impl AvnOptionalDateTime {\n\
         \x20   /// Truncates sub-100ns precision toward the Unix epoch.\n\
         \x20   /// Panics if the resulting ticks are outside .NET DateTime.\n\
         \x20   pub fn from_date_time(value: Option<std::time::SystemTime>) -> Self {\n\
         \x20       Self::try_from_date_time(value).expect(\"SystemTime is not representable as .NET DateTime ticks\")\n\
         \x20   }\n\
         \x20   /// Truncates sub-100ns precision toward the Unix epoch; checks the resulting ticks.\n\
         \x20   pub fn try_from_date_time(value: Option<std::time::SystemTime>) -> Result<Self> {\n\
         \x20       match value {\n\
         \x20           Some(time) => {\n\
         \x20               let unix_ticks = match time.duration_since(std::time::UNIX_EPOCH) {\n\
         \x20                   Ok(delta) => duration_ticks(delta)?,\n\
         \x20                   Err(error) => -duration_ticks(error.duration())?,\n\
         \x20               };\n\
         \x20               let ticks = unix_ticks.checked_add(DOTNET_EPOCH_OFFSET_TICKS)\n\
         \x20                   .filter(|ticks| (0..=DOTNET_MAX_DATE_TIME_TICKS).contains(ticks))\n\
         \x20                   .ok_or(Error(hresult::E_INVALIDARG))?;\n\
         \x20               Ok(Self { has_value: 1, ticks })\n\
         \x20           }\n\
         \x20           None => Ok(Self::default()),\n\
         \x20       }\n\
         \x20   }\n\
         \x20   /// Panics for invalid ticks or a date unavailable on the platform.\n\
         \x20   pub fn to_date_time(self) -> Option<std::time::SystemTime> {\n\
         \x20       self.try_to_date_time().expect(\"Invalid .NET DateTime ticks\")\n\
         \x20   }\n\
         \x20   pub fn try_to_date_time(self) -> Result<Option<std::time::SystemTime>> {\n\
         \x20       if self.has_value == 0 {\n\
         \x20           return Ok(None);\n\
         \x20       }\n\
         \x20       if !(0..=DOTNET_MAX_DATE_TIME_TICKS).contains(&self.ticks) {\n\
         \x20           return Err(Error(hresult::E_INVALIDARG));\n\
         \x20       }\n\
         \x20       let unix_ticks = self.ticks - DOTNET_EPOCH_OFFSET_TICKS;\n\
         \x20       let delta = ticks_duration(unix_ticks.unsigned_abs());\n\
         \x20       let time = if unix_ticks < 0 {\n\
         \x20           std::time::UNIX_EPOCH.checked_sub(delta)\n\
         \x20       } else {\n\
         \x20           std::time::UNIX_EPOCH.checked_add(delta)\n\
         \x20       };\n\
         \x20       time.map(Some).ok_or(Error(hresult::E_INVALIDARG))\n\
         \x20   }\n\
         }\n\n\
         /// Ticks between 0001-01-01 and 1970-01-01 in 100ns units.\n\
         pub const DOTNET_EPOCH_OFFSET_TICKS: i64 = 621_355_968_000_000_000;\n\n\
         pub const DOTNET_MAX_DATE_TIME_TICKS: i64 = 3_155_378_975_999_999_999;\n\n\
         fn duration_ticks(value: core::time::Duration) -> Result<i64> {\n\
         \x20   i64::try_from(value.as_secs()).ok()\n\
         \x20       .and_then(|seconds| seconds.checked_mul(10_000_000))\n\
         \x20       .and_then(|ticks| ticks.checked_add(i64::from(value.subsec_nanos() / 100)))\n\
         \x20       .ok_or(Error(hresult::E_INVALIDARG))\n\
         }\n\n\
         fn ticks_duration(ticks: u64) -> core::time::Duration {\n\
         \x20   core::time::Duration::new(ticks / 10_000_000, ((ticks % 10_000_000) * 100) as u32)\n\
         }\n\n\
         /// Blittable ABI mirror of a nullable TimeSpan tick count.\n\
         #[repr(C)]\n\
         #[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n\
         pub struct AvnOptionalTimeSpan {\n\
         \x20   pub has_value: i32,\n\
         \x20   pub ticks: i64,\n\
         }\n\n\
         impl AvnOptionalTimeSpan {\n\
         \x20   /// Truncates sub-100ns precision toward zero.\n\
         \x20   /// Panics if the resulting ticks exceed TimeSpan.\n\
         \x20   pub fn from_duration(value: Option<core::time::Duration>) -> Self {\n\
         \x20       Self::try_from_duration(value).expect(\"Duration is not representable as .NET TimeSpan ticks\")\n\
         \x20   }\n\
         \x20   /// Truncates sub-100ns precision toward zero; checks the resulting ticks.\n\
         \x20   pub fn try_from_duration(value: Option<core::time::Duration>) -> Result<Self> {\n\
         \x20       match value {\n\
         \x20           Some(duration) => Ok(Self {\n\
         \x20               has_value: 1,\n\
         \x20               ticks: duration_ticks(duration)?,\n\
         \x20           }),\n\
         \x20           None => Ok(Self::default()),\n\
         \x20       }\n\
         \x20   }\n\
         \x20   /// Panics for a negative TimeSpan, which Duration cannot represent.\n\
         \x20   pub fn to_duration(self) -> Option<core::time::Duration> {\n\
         \x20       self.try_to_duration().expect(\"Negative .NET TimeSpan cannot be represented as Duration\")\n\
         \x20   }\n\
         \x20   pub fn try_to_duration(self) -> Result<Option<core::time::Duration>> {\n\
         \x20       if self.has_value == 0 {\n\
         \x20           return Ok(None);\n\
         \x20       }\n\
         \x20       let ticks = u64::try_from(self.ticks).map_err(|_| Error(hresult::E_INVALIDARG))?;\n\
         \x20       Ok(Some(ticks_duration(ticks)))\n\
         \x20   }\n\
         }\n\n\
         /// Blittable ABI mirror of Avalonia.PixelPoint.\n\
         #[repr(C)]\n\
         #[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]\n\
         pub struct AvnPixelPoint {\n\
         \x20   pub x: i32,\n\
         \x20   pub y: i32,\n\
         }\n\n",
    );
    if ir
        .types
        .iter()
        .any(|t| t.properties.iter().any(|p| p.kind == "Variant"))
    {
        out.push_str(&variant::emit_sys_struct());
        out.push('\n');
    }
    if ir.brush_interface_name.is_some() {
        out.push_str(&emit_brush(ir));
        out.push('\n');
    }
    if ir.command_interface_name.is_some() {
        out.push_str(&emit_command(ir));
        out.push('\n');
    }
    if ir.template_interface_name.is_some() {
        out.push_str(&emit_data_template(ir));
        out.push('\n');
    }
    if ir.item_filter_interface_name.is_some() || ir.text_filter_interface_name.is_some() {
        out.push_str(&emit_filters(ir));
        out.push('\n');
    }
    if ir.item_selector_interface_name.is_some() || ir.text_selector_interface_name.is_some() {
        out.push_str(&emit_selectors(ir));
        out.push('\n');
    }
    if ir.popup_placement_interface_name.is_some() {
        out.push_str(&emit_popup_placement(ir));
        out.push('\n');
    }
    if ir.async_populator_interface_name.is_some() {
        out.push_str(&emit_async_populator(ir));
        out.push('\n');
    }
    if ir.notification_interface_name.is_some() {
        out.push_str(&emit_notification(ir));
        out.push('\n');
    }
    for event in unique_events(ir) {
        out.push_str(&emit_event_handler(event));
        out.push('\n');
    }
    let mut emitted_collections = Vec::new();
    for collection in ir
        .types
        .iter()
        .flat_map(|t| t.properties.iter())
        .filter(|p| p.kind == "ComCollection")
    {
        let name = collection
            .interface_name
            .as_deref()
            .expect("collection interfaceName");
        if !emitted_collections.contains(&name) {
            out.push_str(&emit_collection(collection));
            out.push('\n');
            emitted_collections.push(name);
        }
    }
    for ty in ir
        .types
        .iter()
        .filter(|t| t.kind == "Interface" || t.kind == "Class")
    {
        out.push_str(&emit_interface(ir, ty));
        out.push('\n');
    }
    for properties in attached_property_groups(ir) {
        out.push_str(&emit_attached_statics(&properties));
        out.push('\n');
    }
    if ir.types.iter().any(|t| t.is_constructible) {
        out.push_str(&emit_factory(ir));
    }
    out
}

fn emit_collection(collection: &ProjectedProperty) -> String {
    let interface_name = simple_name(
        collection
            .interface_name
            .as_deref()
            .expect("collection interfaceName"),
    );
    let element_kind = collection
        .element_kind
        .as_deref()
        .expect("collection elementKind");
    let element_name = collection
        .element_interface_name
        .as_deref()
        .map(simple_name);
    let abi_type = rust_abi_type(
        element_kind,
        collection.element_interface_name.as_deref(),
        false,
    );
    let iid = collection
        .interface_iid
        .as_deref()
        .expect("collection interfaceIid");
    let iid_const = format!("{}_IID", to_shouty(interface_name));
    let mut out = format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[repr(C)]\n\
         struct {interface_name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   get_count: unsafe extern \"system\" fn(*mut {interface_name}, *mut i32) -> i32,\n\
         \x20   get_at: unsafe extern \"system\" fn(*mut {interface_name}, i32, *mut {abi_type}) -> i32,\n\
         \x20   add: unsafe extern \"system\" fn(*mut {interface_name}, {abi_type}) -> i32,\n\
         \x20   index_of: unsafe extern \"system\" fn(*mut {interface_name}, {abi_type}, *mut i32) -> i32,\n\
         \x20   remove_at: unsafe extern \"system\" fn(*mut {interface_name}, i32) -> i32,\n\
         \x20   clear: unsafe extern \"system\" fn(*mut {interface_name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {interface_name} {{\n\
         \x20   vtbl: *const {interface_name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {interface_name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{interface_name}> {{\n\
         \x20   pub fn len(&self) -> Result<usize> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_count)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value as usize)\n\
         \x20       }}\n\
         \x20   }}\n\
        \x20   pub fn is_empty(&self) -> Result<bool> {{\n\
        \x20       Ok(self.len()? == 0)\n\
        \x20   }}\n\
",
        iid = guid_literal(iid)
    );
    match element_kind {
        "ComInterface" => {
            let element_name = element_name.expect("COM collection elementInterfaceName");
            out.push_str(&format!(
                "    pub fn get(&self, index: usize) -> Result<ComPtr<{element_name}>> {{\n\
                 \x20       unsafe {{\n\
                 \x20           let mut value = ptr::null_mut();\n\
                 \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
                 \x20           hresult::check(hr)?;\n\
                 \x20           ComPtr::from_projected_raw(value)\n\
                 \x20       }}\n\
                 \x20   }}\n\
                 \x20   pub fn add(&self, value: &ComPtr<{element_name}>) -> Result<()> {{\n\
                 \x20       unsafe {{ hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_raw())) }}\n\
                 \x20   }}\n\
                 \x20   pub fn index_of(&self, value: &ComPtr<{element_name}>) -> Result<Option<usize>> {{\n\
                 \x20       unsafe {{\n\
                 \x20           let mut index = -1;\n\
                 \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value.as_raw(), &mut index);\n\
                 \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
                 \x20       }}\n\
                 \x20   }}\n"
            ));
        }
        "StringUtf16" => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<*mut u16> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: &[u16]) -> Result<()> {\n\
             \x20       let value = crate::terminated_utf16(value);\n\
             \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value.as_ptr().cast_mut())) }\n\
             \x20   }\n\
             \x20   pub fn index_of(&self, value: &[u16]) -> Result<Option<usize>> {\n\
             \x20       let value = crate::terminated_utf16(value);\n\
             \x20       unsafe {\n\
             \x20           let mut index = -1;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value.as_ptr().cast_mut(), &mut index);\n\
             \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
             \x20       }\n\
             \x20   }\n",
        ),
        "Variant" => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<AvnVariant> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = AvnVariant::default();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: AvnVariant) -> Result<()> {\n\
             \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value)) }\n\
             \x20   }\n\
             \x20   pub fn index_of(&self, value: AvnVariant) -> Result<Option<usize>> {\n\
             \x20       unsafe {\n\
             \x20           let mut index = -1;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value, &mut index);\n\
             \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
             \x20       }\n\
             \x20   }\n",
        ),
        "DateTimeI64" => out.push_str(
            "    pub fn get(&self, index: usize) -> Result<i64> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = 0i64;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_at)(self.as_raw(), index as i32, &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n\
             \x20   pub fn add(&self, value: i64) -> Result<()> {\n\
             \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().add)(self.as_raw(), value)) }\n\
             \x20   }\n\
             \x20   pub fn index_of(&self, value: i64) -> Result<Option<usize>> {\n\
             \x20       unsafe {\n\
             \x20           let mut index = -1;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().index_of)(self.as_raw(), value, &mut index);\n\
             \x20           hresult::check(hr).map(|_| (index >= 0).then_some(index as usize))\n\
             \x20       }\n\
             \x20   }\n",
        ),
        _ => panic!("unsupported collection element kind {element_kind}"),
    }
    out.push_str(
        "    pub fn remove(&self, index: usize) -> Result<()> {\n\
         \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().remove_at)(self.as_raw(), index as i32)) }\n\
         \x20   }\n\
         \x20   pub fn clear(&self) -> Result<()> {\n\
         \x20       unsafe { hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().clear)(self.as_raw())) }\n\
         \x20   }\n\
         }\n",
    );
    out
}

fn emit_brush(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.brush_interface_name
            .as_deref()
            .expect("brushInterfaceName"),
    );
    let iid = ir
        .brush_interface_iid
        .as_deref()
        .expect("brushInterfaceIid for a projected brush");
    let iid_const = format!("{}_IID", to_shouty(name));
    let color = geometry::find("Color")
        .expect("Color geometry struct")
        .abi_name;
    format!(
        "/// A brush projected as a solid colour: a packed `{color}` plus an opacity.\n\
         ///\n\
         /// Read-only: the managed side hands out immutable brushes, so a new brush is minted\n\
         /// through `IAvnControlFactory::create_solid_color_brush`. Reading a gradient, drawing\n\
         /// or visual brush fails rather than degrading to a nearest colour.\n\
         pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   get_color: unsafe extern \"system\" fn(*mut {name}, *mut {color}) -> i32,\n\
         \x20   get_opacity: unsafe extern \"system\" fn(*mut {name}, *mut f64) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn color(&self) -> Result<{color}> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value: {color} = Default::default();\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_color)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn opacity(&self) -> Result<f64> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0.0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_opacity)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr).map(|_| value)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
        iid_literal = guid_literal(iid)
    )
}

fn emit_command(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.command_interface_name
            .as_deref()
            .expect("commandInterfaceName"),
    );
    let iid = ir
        .command_interface_iid
        .as_deref()
        .expect("commandInterfaceIid for a projected command");
    let iid_const = format!("{}_IID", to_shouty(name));
    let handler_name = simple_name(
        ir.command_handler_interface_name
            .as_deref()
            .expect("commandHandlerInterfaceName for a projected command"),
    );
    let handler_iid = ir
        .command_handler_interface_iid
        .as_deref()
        .expect("commandHandlerInterfaceIid for a projected command");
    let handler_iid_const = format!("{}_IID", to_shouty(&handler_name));
    let handler_stem = handler_name
        .strip_prefix("IAvn")
        .unwrap_or(&handler_name)
        .strip_suffix("Handler")
        .unwrap_or(&handler_name);
    let handler_fn = format!("{}_handler", to_snake(handler_stem));
    let handler_shouty = to_shouty(&handler_name);
    format!(
        "pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   execute: unsafe extern \"system\" fn(*mut {name}, AvnVariant) -> i32,\n\
         \x20   can_execute: unsafe extern \"system\" fn(*mut {name}, AvnVariant, *mut i32) -> i32,\n\
         \x20   advise_can_execute_changed: unsafe extern \"system\" fn(*mut {name}, *mut {handler_name}, *mut i64) -> i32,\n\
         \x20   unadvise_can_execute_changed: unsafe extern \"system\" fn(*mut {name}, i64) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn execute(&self, parameter: AvnVariant) -> Result<()> {{\n\
         \x20       unsafe {{ hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().execute)(self.as_raw(), parameter)) }}\n\
         \x20   }}\n\
         \x20   pub fn can_execute(&self, parameter: AvnVariant) -> Result<bool> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().can_execute)(self.as_raw(), parameter, &mut value);\n\
         \x20           hresult::check(hr).map(|_| value != 0)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn advise_can_execute_changed(\n\
         \x20       &self,\n\
         \x20       handler: &ComPtr<{handler_name}>,\n\
         \x20   ) -> Result<i64> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut subscription_id = 0i64;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().advise_can_execute_changed)(\n\
         \x20               self.as_raw(),\n\
         \x20               handler.as_raw(),\n\
         \x20               &mut subscription_id,\n\
         \x20           );\n\
         \x20           hresult::check(hr).map(|_| subscription_id)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn unadvise_can_execute_changed(&self, subscription_id: i64) -> Result<()> {{\n\
         \x20       unsafe {{ hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().unadvise_can_execute_changed)(self.as_raw(), subscription_id)) }}\n\
         \x20   }}\n\
         }}\n\n\
         pub const {handler_iid_const}: Guid = {handler_iid_literal};\n\n\
         #[repr(C)]\n\
         struct {handler_name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {handler_name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {handler_name} {{\n\
         \x20   vtbl: *const {handler_name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {handler_name} {{\n\
         \x20   const IID: Guid = {handler_iid_const};\n\
         }}\n\n\
         impl ComPtr<{handler_name}> {{\n\
         \x20   pub fn invoke(&self) -> Result<()> {{\n\
         \x20       unsafe {{ hresult::check(((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw())) }}\n\
         \x20   }}\n\
         }}\n\n\
         pub fn {handler_fn}(mut callback: impl FnMut() -> Result<()> + Send + 'static) -> ComPtr<{handler_name}> {{\n\
         \x20   crate::event_callback::create::<{handler_name}, ()>({handler_name} {{ vtbl: &{handler_shouty}_VTBL }}, move |_| callback())\n\
         }}\n\n\
         unsafe extern \"system\" fn {handler_fn}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{handler_name}, ()>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {handler_fn}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{handler_name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {handler_fn}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{handler_name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {handler_fn}_invoke(this: *mut {handler_name}) -> i32 {{\n\
         \x20   crate::event_callback::invoke::<{handler_name}, ()>(this, &mut ())\n\
         }}\n\n\
         #[rustfmt::skip]\n\
         static {handler_shouty}_VTBL: {handler_name}Vtbl = {handler_name}Vtbl {{\n\
         \x20   query_interface: {handler_fn}_query_interface,\n\
         \x20   add_ref: {handler_fn}_add_ref,\n\
         \x20   release: {handler_fn}_release,\n\
         \x20   invoke: {handler_fn}_invoke,\n\
         }};\n",
        iid_literal = guid_literal(iid),
        handler_iid_literal = guid_literal(handler_iid),
    )
}

fn emit_data_template(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.template_interface_name
            .as_deref()
            .expect("templateInterfaceName"),
    );
    let iid = ir
        .template_interface_iid
        .as_deref()
        .expect("templateInterfaceIid for a projected data template");
    let iid_const = format!("{}_IID", to_shouty(name));
    format!(
        "pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   match_: unsafe extern \"system\" fn(*mut {name}, AvnVariant, *mut i32) -> i32,\n\
         \x20   build: unsafe extern \"system\" fn(*mut {name}, *mut *mut IAvnControl) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn matches(&self, data: AvnVariant) -> Result<bool> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().match_)(self.as_raw(), data, &mut value);\n\
         \x20           hresult::check(hr).map(|_| value != 0)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn build(&self) -> Result<ComPtr<IAvnControl>> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut value = ptr::null_mut();\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().build)(self.as_raw(), &mut value);\n\
         \x20           hresult::check(hr)?;\n\
         \x20           ComPtr::from_projected_raw(value)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
        iid_literal = guid_literal(iid),
    )
}

fn emit_filters(ir: &ProjectionIr) -> String {
    let mut out = String::new();
    if let (Some(name_full), Some(iid)) = (
        ir.item_filter_interface_name.as_deref(),
        ir.item_filter_interface_iid.as_deref(),
    ) {
        let name = simple_name(name_full);
        let iid_const = format!("{}_IID", to_shouty(name));
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {iid};\n\n\
             #[repr(C)]\n\
             struct {name}Vtbl {{\n\
             \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
             \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   invoke: unsafe extern \"system\" fn(*mut {name}, *const u16, AvnVariant, *mut i32) -> i32,\n\
             }}\n\n\
             #[repr(C)]\n\
             pub struct {name} {{\n\
             \x20   vtbl: *const {name}Vtbl,\n\
             }}\n\n\
             unsafe impl ComInterface for {name} {{\n\
             \x20   const IID: Guid = {iid_const};\n\
             }}\n\n\
             impl ComPtr<{name}> {{\n\
             \x20   pub fn invoke(&self, search: *const u16, item: AvnVariant) -> Result<bool> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut result = 0;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw(), search, item, &mut result);\n\
             \x20           hresult::check(hr).map(|_| result != 0)\n\
             \x20       }}\n\
             \x20   }}\n\
             }}\n",
            iid = guid_literal(iid),
        ));
    }
    if let (Some(name_full), Some(iid)) = (
        ir.text_filter_interface_name.as_deref(),
        ir.text_filter_interface_iid.as_deref(),
    ) {
        let name = simple_name(name_full);
        let iid_const = format!("{}_IID", to_shouty(name));
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {iid};\n\n\
             #[repr(C)]\n\
             struct {name}Vtbl {{\n\
             \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
             \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   invoke: unsafe extern \"system\" fn(*mut {name}, *const u16, *const u16, *mut i32) -> i32,\n\
             }}\n\n\
             #[repr(C)]\n\
             pub struct {name} {{\n\
             \x20   vtbl: *const {name}Vtbl,\n\
             }}\n\n\
             unsafe impl ComInterface for {name} {{\n\
             \x20   const IID: Guid = {iid_const};\n\
             }}\n\n\
             impl ComPtr<{name}> {{\n\
             \x20   pub fn invoke(&self, search: *const u16, item: *const u16) -> Result<bool> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut result = 0;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw(), search, item, &mut result);\n\
             \x20           hresult::check(hr).map(|_| result != 0)\n\
             \x20       }}\n\
             \x20   }}\n\
             }}\n",
            iid = guid_literal(iid),
        ));
    }
    out
}

fn emit_selectors(ir: &ProjectionIr) -> String {
    let mut out = String::new();
    if let (Some(name_full), Some(iid)) = (
        ir.item_selector_interface_name.as_deref(),
        ir.item_selector_interface_iid.as_deref(),
    ) {
        let name = simple_name(name_full);
        let iid_const = format!("{}_IID", to_shouty(name));
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {iid};\n\n\
             #[repr(C)]\n\
             struct {name}Vtbl {{\n\
             \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
             \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   invoke: unsafe extern \"system\" fn(*mut {name}, *const u16, AvnVariant, *mut *mut u16) -> i32,\n\
             }}\n\n\
             #[repr(C)]\n\
             pub struct {name} {{\n\
             \x20   vtbl: *const {name}Vtbl,\n\
             }}\n\n\
             unsafe impl ComInterface for {name} {{\n\
             \x20   const IID: Guid = {iid_const};\n\
             }}\n\n\
             impl ComPtr<{name}> {{\n\
             \x20   pub fn invoke(&self, search: *const u16, item: AvnVariant) -> Result<*mut u16> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut text: *mut u16 = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw(), search, item, &mut text);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           Ok(text)\n\
             \x20       }}\n\
             \x20   }}\n\
             }}\n",
            iid = guid_literal(iid),
        ));
    }
    if let (Some(name_full), Some(iid)) = (
        ir.text_selector_interface_name.as_deref(),
        ir.text_selector_interface_iid.as_deref(),
    ) {
        let name = simple_name(name_full);
        let iid_const = format!("{}_IID", to_shouty(name));
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {iid};\n\n\
             #[repr(C)]\n\
             struct {name}Vtbl {{\n\
             \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
             \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
             \x20   invoke: unsafe extern \"system\" fn(*mut {name}, *const u16, *const u16, *mut *mut u16) -> i32,\n\
             }}\n\n\
             #[repr(C)]\n\
             pub struct {name} {{\n\
             \x20   vtbl: *const {name}Vtbl,\n\
             }}\n\n\
             unsafe impl ComInterface for {name} {{\n\
             \x20   const IID: Guid = {iid_const};\n\
             }}\n\n\
             impl ComPtr<{name}> {{\n\
             \x20   pub fn invoke(&self, search: *const u16, item: *const u16) -> Result<*mut u16> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut text: *mut u16 = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw(), search, item, &mut text);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           Ok(text)\n\
             \x20       }}\n\
             \x20   }}\n\
             }}\n",
            iid = guid_literal(iid),
        ));
    }
    out
}

fn emit_async_populator(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.async_populator_interface_name
            .as_deref()
            .expect("asyncPopulatorInterfaceName"),
    );
    let iid = ir
        .async_populator_interface_iid
        .as_deref()
        .expect("asyncPopulatorInterfaceIid");
    let iid_const = format!("{}_IID", to_shouty(name));
    let completion_name = simple_name(
        ir.async_populator_completion_interface_name
            .as_deref()
            .expect("asyncPopulatorCompletionInterfaceName"),
    );
    let completion_iid = ir
        .async_populator_completion_interface_iid
        .as_deref()
        .expect("asyncPopulatorCompletionInterfaceIid");
    let completion_iid_const = format!("{}_IID", to_shouty(completion_name));
    format!(
        "pub const {completion_iid_const}: Guid = {completion_iid_literal};\n\n\
         #[repr(C)]\n\
         struct {completion_name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   complete: unsafe extern \"system\" fn(*mut {completion_name}, i64, i32, *mut IAvnVariantList) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {completion_name} {{\n\
         \x20   vtbl: *const {completion_name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {completion_name} {{\n\
         \x20   const IID: Guid = {completion_iid_const};\n\
         }}\n\n\
         impl ComPtr<{completion_name}> {{\n\
         \x20   pub fn complete(&self, request_id: i64, hresult_value: i32, items: *mut IAvnVariantList) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().complete)(self.as_raw(), request_id, hresult_value, items);\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n\n\
         pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   begin_populate: unsafe extern \"system\" fn(*mut {name}, i64, *mut {completion_name}, *const u16) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn begin_populate(&self, request_id: i64, completion: *mut {completion_name}, search: *const u16) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().begin_populate)(self.as_raw(), request_id, completion, search);\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
        completion_iid_literal = guid_literal(completion_iid),
        iid_literal = guid_literal(iid),
    )
}

fn emit_popup_placement(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.popup_placement_interface_name
            .as_deref()
            .expect("popupPlacementInterfaceName"),
    );
    let iid = ir
        .popup_placement_interface_iid
        .as_deref()
        .expect("popupPlacementInterfaceIid");
    let iid_const = format!("{}_IID", to_shouty(name));
    let placement_name = format!("{}Result", name.strip_prefix("IAvn").unwrap_or(name));
    format!(
        "pub const {iid_const}: Guid = {iid_literal};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}, f64, f64, f64, f64, f64, f64, *mut f64, *mut f64, *mut i32, *mut i32, *mut i32) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         /// The callback's placement result: the offset and the anchor/gravity/\n\
         /// constraint adjustments the popup positioner should apply.\n\
         pub struct {placement} {{\n\
         \x20   pub offset_x: f64,\n\
         \x20   pub offset_y: f64,\n\
         \x20   pub anchor: i32,\n\
         \x20   pub gravity: i32,\n\
         \x20   pub constraint_adjustment: i32,\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn invoke(&self, popup_width: f64, popup_height: f64, anchor_x: f64, anchor_y: f64, anchor_width: f64, anchor_height: f64) -> Result<{placement}> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut offset_x = 0.0;\n\
         \x20           let mut offset_y = 0.0;\n\
         \x20           let mut anchor = 0;\n\
         \x20           let mut gravity = 0;\n\
         \x20           let mut constraint_adjustment = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw(), popup_width, popup_height, anchor_x, anchor_y, anchor_width, anchor_height, &mut offset_x, &mut offset_y, &mut anchor, &mut gravity, &mut constraint_adjustment);\n\
         \x20           hresult::check(hr).map(|_| {placement} {{ offset_x, offset_y, anchor, gravity, constraint_adjustment }})\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n",
        iid_literal = guid_literal(iid),
        placement = placement_name,
    )
}

fn emit_notification(ir: &ProjectionIr) -> String {
    let name = simple_name(
        ir.notification_interface_name
            .as_deref()
            .expect("notificationInterfaceName"),
    );
    let iid = ir
        .notification_interface_iid
        .as_deref()
        .expect("notificationInterfaceIid for a projected notification");
    let handler_iid = ir
        .notification_handler_interface_iid
        .as_deref()
        .expect("notificationHandlerInterfaceIid for a projected notification");
    let iid_const = format!("{}_IID", to_shouty(name));
    let handler = "IAvnNotificationActionHandler";
    let handler_iid_const = format!("{}_IID", to_shouty(handler));
    let handler_shouty = to_shouty(handler);
    format!(
        "pub const {handler_iid_const}: Guid = {handler_iid_literal};

         #[repr(C)]
         struct {handler}Vtbl {{
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,
         \x20   invoke: unsafe extern \"system\" fn(*mut {handler}) -> i32,
         }}

         #[repr(C)]
         pub struct {handler} {{
         \x20   vtbl: *const {handler}Vtbl,
         }}

         unsafe impl ComInterface for {handler} {{
         \x20   const IID: Guid = {handler_iid_const};
         }}

         pub fn notification_action_handler(mut callback: impl FnMut() -> Result<()> + Send + 'static) -> ComPtr<{handler}> {{
         \x20   crate::event_callback::create::<{handler}, ()>({handler} {{ vtbl: &{handler_shouty}_VTBL }}, move |_| callback())
         }}

         unsafe extern \"system\" fn notification_action_handler_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{
         \x20   crate::event_callback::query_interface::<{handler}, ()>(this, iid, result)
         }}

         unsafe extern \"system\" fn notification_action_handler_add_ref(this: *mut IUnknown) -> u32 {{
         \x20   crate::event_callback::add_ref::<{handler}, ()>(this)
         }}

         unsafe extern \"system\" fn notification_action_handler_release(this: *mut IUnknown) -> u32 {{
         \x20   crate::event_callback::release::<{handler}, ()>(this)
         }}

         unsafe extern \"system\" fn notification_action_handler_invoke(this: *mut {handler}) -> i32 {{
         \x20   crate::event_callback::invoke::<{handler}, ()>(this, &mut ())
         }}

         #[rustfmt::skip]
         static {handler_shouty}_VTBL: {handler}Vtbl = {handler}Vtbl {{
         \x20   query_interface: notification_action_handler_query_interface,
         \x20   add_ref: notification_action_handler_add_ref,
         \x20   release: notification_action_handler_release,
         \x20   invoke: notification_action_handler_invoke,
         }};

         pub const {iid_const}: Guid = {iid_literal};

         #[repr(C)]
         struct {name}Vtbl {{
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,
         \x20   get_title: unsafe extern \"system\" fn(*mut {name}, *mut *mut u16) -> i32,
         \x20   get_message: unsafe extern \"system\" fn(*mut {name}, *mut *mut u16) -> i32,
         \x20   get_type: unsafe extern \"system\" fn(*mut {name}, *mut i32) -> i32,
         \x20   get_expiration: unsafe extern \"system\" fn(*mut {name}, *mut i64) -> i32,
         \x20   get_on_click: unsafe extern \"system\" fn(*mut {name}, *mut *mut {handler}) -> i32,
         \x20   get_on_close: unsafe extern \"system\" fn(*mut {name}, *mut *mut {handler}) -> i32,
         }}

         #[repr(C)]
         pub struct {name} {{
         \x20   vtbl: *const {name}Vtbl,
         }}

         unsafe impl ComInterface for {name} {{
         \x20   const IID: Guid = {iid_const};
         }}

         impl ComPtr<{name}> {{
         \x20   pub fn title(&self) -> Result<String> {{
         \x20       unsafe {{
         \x20           let mut value: *mut u16 = ptr::null_mut();
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_title)(self.as_raw(), &mut value);
         \x20           hresult::check(hr)?;
         \x20           crate::clone_utf16(value).ok_or(Error(hresult::E_POINTER))
         \x20       }}
         \x20   }}
         \x20   pub fn message(&self) -> Result<String> {{
         \x20       unsafe {{
         \x20           let mut value: *mut u16 = ptr::null_mut();
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_message)(self.as_raw(), &mut value);
         \x20           hresult::check(hr)?;
         \x20           crate::clone_utf16(value).ok_or(Error(hresult::E_POINTER))
         \x20       }}
         \x20   }}
         \x20   pub fn notification_type(&self) -> Result<i32> {{
         \x20       unsafe {{
         \x20           let mut value = 0;
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_type)(self.as_raw(), &mut value);
         \x20           hresult::check(hr).map(|_| value)
         \x20       }}
         \x20   }}
         \x20   pub fn expiration(&self) -> Result<i64> {{
         \x20       unsafe {{
         \x20           let mut value = 0;
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_expiration)(self.as_raw(), &mut value);
         \x20           hresult::check(hr).map(|_| value)
         \x20       }}
         \x20   }}
         }}
",
        iid_literal = guid_literal(iid),
        handler_iid_literal = guid_literal(handler_iid),
        handler_shouty = handler_shouty,
    )
}

fn emit_interface(ir: &ProjectionIr, ty: &ProjectedType) -> String {
    let mut out = String::new();
    let iid_const = format!("{}_IID", to_shouty(&ty.name));
    if let Some(iid) = &ty.iid {
        out.push_str(&format!(
            "pub const {iid_const}: Guid = {};\n\n",
            guid_literal(iid)
        ));
    }

    out.push_str("#[repr(C)]\n");
    out.push_str(&format!("struct {}Vtbl {{\n", ty.name));
    emit_iunknown_slots(&mut out);
    if ty.kind == "Class" {
        out.push_str(&format!(
            "    get_object_id: unsafe extern \"system\" fn(*mut {}, *mut i64) -> i32,\n\
             \x20   get_lifetime_token: unsafe extern \"system\" fn(*mut {}, *mut i64) -> i32,\n",
            ty.name, ty.name
        ));
    }
    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            emit_property_slots(&mut out, ty, property);
        }
        for method in &owner.methods {
            out.push_str(&format!(
                "    {}: unsafe extern \"system\" fn({}) -> i32,\n",
                to_snake(&method.name),
                vtbl_method_args(ty, method)
            ));
        }
        for event in &owner.events {
            let handler = simple_name(&event.handler_interface_name);
            let snake = to_snake(&event.name);
            out.push_str(&format!(
                "    advise_{snake}: unsafe extern \"system\" fn(*mut {}, *mut {handler}, *mut i64) -> i32,\n\
                 \x20   unadvise_{snake}: unsafe extern \"system\" fn(*mut {}, i64) -> i32,\n",
                ty.name, ty.name
            ));
        }
    }
    out.push_str("}\n\n");

    out.push_str("#[repr(C)]\n");
    out.push_str(&format!(
        "pub struct {} {{\n    vtbl: *const {}Vtbl,\n}}\n\n",
        ty.name, ty.name
    ));
    out.push_str(&format!("unsafe impl ComInterface for {} {{\n", ty.name));
    if ty.iid.is_some() {
        out.push_str(&format!("    const IID: Guid = {iid_const};\n"));
    }
    out.push_str("}\n\n");

    out.push_str(&format!("impl ComPtr<{}> {{\n", ty.name));
    if ty.kind == "Class" {
        out.push_str(
            "    pub fn object_id(&self) -> Result<i64> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = 0;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_object_id)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }\n\
             \x20   }\n",
        );
        out.push_str(
            "    pub fn lifetime_token(&self) -> Result<*mut IUnknown> {\n\
             \x20       unsafe {\n\
             \x20           let mut value = 0i64;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_lifetime_token)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| value as usize as *mut IUnknown)\n\
             \x20       }\n\
             \x20   }\n",
        );
    }
    for owner in lineage(ir, ty) {
        for property in &owner.properties {
            out.push_str(&emit_property(ty, property));
        }
        for method in &owner.methods {
            out.push_str(&emit_method(ty, method));
        }
        for event in &owner.events {
            out.push_str(&emit_event(event));
        }
    }

    out.push_str("}\n");
    out
}

fn emit_event_handler(event: &ProjectedEvent) -> String {
    if event.payload_kind == "Args" {
        return emit_args_event_handler(event);
    }
    if !event.parameters.is_empty() {
        return emit_field_event_handler(event);
    }
    assert_eq!(event.payload_kind, "None", "unsupported event payload kind");
    let name = simple_name(&event.handler_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let stem = to_snake(name);
    format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{\n\
         \x20   vtbl: *const {name}Vtbl,\n\
         }}\n\n\
         unsafe impl ComInterface for {name} {{\n\
         \x20   const IID: Guid = {iid_const};\n\
         }}\n\n\
         impl ComPtr<{name}> {{\n\
         \x20   pub fn invoke(&self) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().invoke)(self.as_raw());\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n\
         }}\n\n\
         static {shouty}_VTBL: {name}Vtbl = {name}Vtbl {{\n\
         \x20   query_interface: {stem}_query_interface,\n\
         \x20   add_ref: {stem}_add_ref,\n\
         \x20   release: {stem}_release,\n\
         \x20   invoke: {stem}_invoke,\n\
         }};\n\n\
         pub fn {handler_fn}(mut callback: impl FnMut() -> Result<()> + Send + 'static) -> ComPtr<{name}> {{\n\
         \x20   crate::event_callback::create::<{name}, ()>({name} {{ vtbl: &{shouty}_VTBL }}, move |_| callback())\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{name}, ()>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{name}, ()>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_invoke(this: *mut {name}) -> i32 {{\n\
         \x20   crate::event_callback::invoke::<{name}, ()>(this, &mut ())\n\
         }}\n",
        iid = guid_literal(&event.handler_interface_iid),
        shouty = to_shouty(name),
        handler_fn = event_handler_function(event),
    )
}

fn emit_args_event_handler(event: &ProjectedEvent) -> String {
    assert_eq!(
        event.payload_kind, "Args",
        "args handler requires Args payload kind"
    );
    let args_full = event
        .args_interface_name
        .as_deref()
        .expect("argsInterfaceName");
    let args_iid = event
        .args_interface_iid
        .as_deref()
        .expect("argsInterfaceIid");
    let args_name = simple_name(args_full);
    let args_iid_const = format!("{}_IID", to_shouty(args_name));
    let name = simple_name(&event.handler_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let shouty = to_shouty(name);
    let stem = to_snake(name);

    // The args interface: count/getter pairs, exposed as safe methods on the
    // raw pointer the handler receives.
    let mut args_slots = String::new();
    let mut args_methods = String::new();
    for parameter in &event.parameters {
        let prop = to_snake(&parameter.name);
        args_slots.push_str(&format!(
            "    get_{prop}_count: unsafe extern \"system\" fn(*mut {args_name}, *mut i32) -> i32,\n\
             \x20   get_{prop}_at: unsafe extern \"system\" fn(*mut {args_name}, i32, *mut AvnVariant) -> i32,\n"
        ));
        args_methods.push_str(&format!(
            "    pub fn {prop}_count(&self) -> Result<i32> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = 0;\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{prop}_count)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }}\n\
             \x20   }}\n\
             \x20   pub fn {prop}_at(&self, index: i32) -> Result<AvnVariant> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = AvnVariant::default();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{prop}_at)(self.as_raw(), index, &mut value);\n\
             \x20           hresult::check(hr).map(|_| value)\n\
             \x20       }}\n\
             \x20   }}\n"
        ));
    }

    format!(
        "pub const {args_iid_const}: Guid = {args_iid_literal};\n\n\
         #[repr(C)]\n\
         struct {args_name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         {args_slots}}}\n\n\
         #[repr(C)]\n\
         pub struct {args_name} {{ vtbl: *const {args_name}Vtbl }}\n\n\
         unsafe impl ComInterface for {args_name} {{ const IID: Guid = {args_iid_const}; }}\n\n\
         impl ComPtr<{args_name}> {{\n\
         {args_methods}}}\n\n\
         pub const {iid_const}: Guid = {iid};\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}, *mut {args_name}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{ vtbl: *const {name}Vtbl }}\n\n\
         unsafe impl ComInterface for {name} {{ const IID: Guid = {iid_const}; }}\n\n\
         static {shouty}_VTBL: {name}Vtbl = {name}Vtbl {{\n\
         \x20   query_interface: {stem}_query_interface,\n\
         \x20   add_ref: {stem}_add_ref,\n\
         \x20   release: {stem}_release,\n\
         \x20   invoke: {stem}_invoke,\n\
         }};\n\n\
         pub fn {handler_fn}(callback: impl FnMut(&mut ComPtr<{args_name}>) -> Result<()> + Send + 'static) -> ComPtr<{name}> {{\n\
         \x20   crate::event_callback::create({name} {{ vtbl: &{shouty}_VTBL }}, callback)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{name}, ComPtr<{args_name}>>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{name}, ComPtr<{args_name}>>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{name}, ComPtr<{args_name}>>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_invoke(this: *mut {name}, args: *mut {args_name}) -> i32 {{\n\
         \x20   let mut arguments = match unsafe {{ ComPtr::from_raw(args) }} {{\n\
         \x20       Some(arguments) => arguments,\n\
         \x20       None => return hresult::E_POINTER,\n\
         \x20   }};\n\
         \x20   let hr = crate::event_callback::invoke::<{name}, ComPtr<{args_name}>>(this, &mut arguments);\n\
         \x20   hr\n\
         }}\n",
        iid = guid_literal(&event.handler_interface_iid),
        args_iid_literal = guid_literal(args_iid),
        handler_fn = event_handler_function(event),
    )
}

fn emit_field_event_handler(event: &ProjectedEvent) -> String {
    assert_eq!(
        event.payload_kind, "Fields",
        "parameterized events require Fields payload kind"
    );
    let name = simple_name(&event.handler_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let shouty = to_shouty(name);
    let stem = to_snake(name);
    let args_name = format!(
        "{}EventArgs",
        name.strip_prefix("IAvn")
            .unwrap_or(name)
            .strip_suffix("Handler")
            .unwrap_or(name)
    );
    let parameters = event
        .parameters
        .iter()
        .map(|parameter| {
            let abi = rust_abi_type(
                &parameter.kind,
                parameter.interface_name.as_deref(),
                parameter.is_nullable,
            );
            if parameter.direction == "InOut" {
                format!(", {}: *mut {abi}", to_snake(&parameter.name))
            } else {
                format!(", {}: {abi}", to_snake(&parameter.name))
            }
        })
        .collect::<String>();
    let fields = event
        .parameters
        .iter()
        .map(|parameter| {
            format!(
                "    pub {}: {},\n",
                to_snake(&parameter.name),
                event_argument_type(parameter)
            )
        })
        .collect::<String>();
    let null_checks = event
        .parameters
        .iter()
        .filter(|parameter| parameter.direction == "InOut")
        .map(|parameter| {
            format!(
                "    if {}.is_null() {{ return hresult::E_POINTER; }}\n",
                to_snake(&parameter.name)
            )
        })
        .collect::<String>();
    let initializers = event
        .parameters
        .iter()
        .map(|parameter| {
            let name = to_snake(&parameter.name);
            let source = match (parameter.kind.as_str(), parameter.direction.as_str()) {
                ("Bool", "InOut") => format!("*{name} != 0"),
                ("Bool", _) => format!("{name} != 0"),
                ("StringUtf16", _) if parameter.is_nullable => {
                    format!("crate::clone_utf16({name})")
                }
                ("StringUtf16", _) => {
                    format!("crate::clone_utf16({name}).unwrap_or_default()")
                }
                (_, "InOut") => format!("*{name}"),
                _ => name.clone(),
            };
            if source == name {
                format!("        {name},\n")
            } else {
                format!("        {name}: {source},\n")
            }
        })
        .collect::<String>();
    let write_backs = event
        .parameters
        .iter()
        .filter(|parameter| parameter.direction == "InOut")
        .map(|parameter| {
            let name = to_snake(&parameter.name);
            let value = if parameter.kind == "Bool" {
                format!("i32::from(arguments.{name})")
            } else {
                format!("arguments.{name}")
            };
            format!("        *{name} = {value};\n")
        })
        .collect::<String>();

    format!(
        "pub const {iid_const}: Guid = {iid};\n\n\
         #[derive(Debug)]\n\
         pub struct {args_name} {{\n\
         {fields}}}\n\n\
         #[repr(C)]\n\
         struct {name}Vtbl {{\n\
         \x20   query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   invoke: unsafe extern \"system\" fn(*mut {name}{parameters}) -> i32,\n\
         }}\n\n\
         #[repr(C)]\n\
         pub struct {name} {{ vtbl: *const {name}Vtbl }}\n\n\
         unsafe impl ComInterface for {name} {{ const IID: Guid = {iid_const}; }}\n\n\
         static {shouty}_VTBL: {name}Vtbl = {name}Vtbl {{\n\
         \x20   query_interface: {stem}_query_interface,\n\
         \x20   add_ref: {stem}_add_ref,\n\
         \x20   release: {stem}_release,\n\
         \x20   invoke: {stem}_invoke,\n\
         }};\n\n\
         pub fn {handler_fn}(callback: impl FnMut(&mut {args_name}) -> Result<()> + Send + 'static) -> ComPtr<{name}> {{\n\
         \x20   crate::event_callback::create({name} {{ vtbl: &{shouty}_VTBL }}, callback)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_query_interface(this: *mut IUnknown, iid: *const Guid, result: *mut *mut c_void) -> i32 {{\n\
         \x20   crate::event_callback::query_interface::<{name}, {args_name}>(this, iid, result)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_add_ref(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::add_ref::<{name}, {args_name}>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_release(this: *mut IUnknown) -> u32 {{\n\
         \x20   crate::event_callback::release::<{name}, {args_name}>(this)\n\
         }}\n\n\
         unsafe extern \"system\" fn {stem}_invoke(this: *mut {name}{parameters}) -> i32 {{\n\
         {null_checks}    let mut arguments = {args_name} {{\n\
         {initializers}    }};\n\
         \x20   let hr = crate::event_callback::invoke::<{name}, {args_name}>(this, &mut arguments);\n\
         \x20   if hr >= 0 {{\n\
         {write_backs}    }}\n\
         \x20   hr\n\
         }}\n",
        iid = guid_literal(&event.handler_interface_iid),
        handler_fn = event_handler_function(event),
    )
}

fn event_argument_type(parameter: &ProjectedParameter) -> String {
    if let Some(geometry) = geometry::find(&parameter.kind) {
        return if parameter.is_nullable {
            geometry.optional_abi_name()
        } else {
            geometry.abi_name.into()
        };
    }
    match parameter.kind.as_str() {
        "I32" => "i32".into(),
        "I64" => "i64".into(),
        "TimeSpanI64" if parameter.is_nullable => "AvnOptionalTimeSpan".into(),
        "TimeSpanI64" => "i64".into(),
        "DateTimeI64" if parameter.is_nullable => "AvnOptionalDateTime".into(),
        "DateTimeI64" => "i64".into(),
        "PixelPointI32" => "AvnPixelPoint".into(),
        "F32" => "f32".into(),
        "F64" => "f64".into(),
        "Bool" => "bool".into(),
        "NullableBool" => "Option<bool>".into(),
        "Variant" => "AvnVariant".into(),
        "StringUtf16" if parameter.is_nullable => "Option<String>".into(),
        "StringUtf16" => "String".into(),
        _ => panic!("unsupported event argument kind {}", parameter.kind),
    }
}

fn emit_event(event: &ProjectedEvent) -> String {
    let snake = to_snake(&event.name);
    let handler = simple_name(&event.handler_interface_name);
    format!(
        "    pub fn advise_{snake}(&self, handler: &ComPtr<{handler}>) -> Result<i64> {{\n\
         \x20       unsafe {{\n\
         \x20           let mut subscription_id = 0;\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().advise_{snake})(self.as_raw(), handler.as_raw(), &mut subscription_id);\n\
         \x20           hresult::check(hr).map(|_| subscription_id)\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   pub fn unadvise_{snake}(&self, subscription_id: i64) -> Result<()> {{\n\
         \x20       unsafe {{\n\
         \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().unadvise_{snake})(self.as_raw(), subscription_id);\n\
         \x20           hresult::check(hr)\n\
         \x20       }}\n\
         \x20   }}\n"
    )
}

fn emit_factory(ir: &ProjectionIr) -> String {
    let mut types: Vec<_> = ir.types.iter().filter(|t| t.is_constructible).collect();
    types.sort_by(|left, right| left.full_name.cmp(&right.full_name));
    let iid = ir
        .factory_iid
        .as_deref()
        .expect("constructible projection requires factoryIid");
    let mut out = format!(
        "pub const IAVN_CONTROL_FACTORY_IID: Guid = {};\n\n",
        guid_literal(iid)
    );
    out.push_str("#[repr(C)]\nstruct IAvnControlFactoryVtbl {\n");
    emit_iunknown_slots(&mut out);
    for ty in &types {
        out.push_str(&format!(
            "    create_{}: unsafe extern \"system\" fn(*mut IAvnControlFactory, *mut *mut {}) -> i32,\n",
            to_snake(interface_suffix(&ty.name)),
            ty.name
        ));
    }
    for properties in attached_property_groups(ir) {
        let first = properties[0];
        let interface_name = simple_name(&first.statics_interface_name);
        out.push_str(&format!(
            "    get_{}_statics: unsafe extern \"system\" fn(*mut IAvnControlFactory, *mut *mut {}) -> i32,\n",
            to_snake(&first.owner_name),
            interface_name
        ));
    }
    if let Some(brush) = ir.brush_interface_name.as_deref() {
        let brush = simple_name(brush);
        let color = geometry::find("Color")
            .expect("Color geometry struct")
            .abi_name;
        out.push_str(&format!(
            "    create_solid_color_brush: unsafe extern \"system\" fn(*mut IAvnControlFactory, {color}, f64, *mut *mut {brush}) -> i32,\n"
        ));
    }
    out.push_str("}\n\n#[repr(C)]\npub struct IAvnControlFactory {\n    vtbl: *const IAvnControlFactoryVtbl,\n}\n\n");
    out.push_str("unsafe impl ComInterface for IAvnControlFactory {\n    const IID: Guid = IAVN_CONTROL_FACTORY_IID;\n}\n\n");
    out.push_str("impl ComPtr<IAvnControlFactory> {\n");
    for ty in types {
        let suffix = interface_suffix(&ty.name);
        out.push_str(&format!(
            "    pub fn create_{}(&self) -> Result<ComPtr<{}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_{})(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_projected_raw(value)\n\
             \x20       }}\n\
             \x20   }}\n",
            to_snake(suffix),
            ty.name,
            to_snake(suffix)
        ));
    }
    for properties in attached_property_groups(ir) {
        let first = properties[0];
        let owner = to_snake(&first.owner_name);
        let interface_name = simple_name(&first.statics_interface_name);
        out.push_str(&format!(
            "    pub fn get_{owner}_statics(&self) -> Result<ComPtr<{interface_name}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{owner}_statics)(self.as_raw(), &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))\n\
             \x20       }}\n\
             \x20   }}\n"
        ));
    }
    if let Some(brush) = ir.brush_interface_name.as_deref() {
        let brush = simple_name(brush);
        let color = geometry::find("Color")
            .expect("Color geometry struct")
            .abi_name;
        out.push_str(&format!(
            "    pub fn create_solid_color_brush(&self, color: {color}, opacity: f64) -> Result<ComPtr<{brush}>> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value = ptr::null_mut();\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().create_solid_color_brush)(self.as_raw(), color, opacity, &mut value);\n\
             \x20           hresult::check(hr)?;\n\
             \x20           ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))\n\
             \x20       }}\n\
             \x20   }}\n"
        ));
    }
    out.push_str("}\n");
    out
}

fn emit_attached_statics(properties: &[&ProjectedAttachedProperty]) -> String {
    let first = properties[0];
    let name = simple_name(&first.statics_interface_name);
    let iid_const = format!("{}_IID", to_shouty(name));
    let mut out = format!(
        "pub const {iid_const}: Guid = {};\n\n#[repr(C)]\nstruct {name}Vtbl {{\n",
        guid_literal(&first.statics_interface_iid)
    );
    emit_iunknown_slots(&mut out);
    for property in properties {
        let snake = to_snake(&property.name);
        let abi_type = rust_abi_type(&property.kind, None, property.is_nullable);
        out.push_str(&format!(
            "    get_{snake}: unsafe extern \"system\" fn(*mut {name}, *mut IAvnControl, *mut {abi_type}) -> i32,\n\
             \x20   set_{snake}: unsafe extern \"system\" fn(*mut {name}, *mut IAvnControl, {abi_type}) -> i32,\n"
        ));
    }
    out.push_str(&format!(
        "}}\n\n#[repr(C)]\npub struct {name} {{\n    vtbl: *const {name}Vtbl,\n}}\n\n\
         unsafe impl ComInterface for {name} {{\n    const IID: Guid = {iid_const};\n}}\n\n\
         impl ComPtr<{name}> {{\n"
    ));
    for property in properties {
        let snake = to_snake(&property.name);
        let abi_type = rust_abi_type(&property.kind, None, property.is_nullable);
        let result = match property.kind.as_str() {
            "Bool" => "value != 0",
            _ => "value",
        };
        let input = match property.kind.as_str() {
            "Bool" => "i32::from(value)".to_string(),
            "StringUtf16" => "value.as_ptr().cast_mut()".to_string(),
            _ => "value".to_string(),
        };
        // A string attached property reads back as the raw pointer the caller owns and writes
        // from a borrowed UTF-16 buffer, exactly like an ordinary string property; every other
        // kind is a scalar that crosses by value.
        let get_type = match property.kind.as_str() {
            "Bool" => "bool".to_string(),
            _ => rust_abi_type(&property.kind, None, property.is_nullable),
        };
        let set_type = match property.kind.as_str() {
            "Bool" => "bool".to_string(),
            "StringUtf16" => "&[u16]".to_string(),
            _ => rust_abi_type(&property.kind, None, property.is_nullable),
        };
        let prepare = prepare_string_input(&property.kind, "value", false);
        out.push_str(&format!(
            "    pub fn get_{snake}(&self, target: &ComPtr<IAvnControl>) -> Result<{get_type}> {{\n\
             \x20       unsafe {{\n\
             \x20           let mut value: {abi_type} = {};\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{snake})(self.as_raw(), target.as_raw(), &mut value);\n\
             \x20           hresult::check(hr).map(|_| {result})\n\
             \x20       }}\n\
             \x20   }}\n\
             \x20   pub fn set_{snake}(&self, target: &ComPtr<IAvnControl>, value: {set_type}) -> Result<()> {{\n\
             {prepare}\
             \x20       unsafe {{\n\
             \x20           let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_{snake})(self.as_raw(), target.as_raw(), {input});\n\
             \x20           hresult::check(hr)\n\
             \x20       }}\n\
             \x20   }}\n",
            rust_abi_default(&property.kind)
        ));
    }
    out.push_str("}\n");
    out
}

fn attached_property_groups(ir: &ProjectionIr) -> Vec<Vec<&ProjectedAttachedProperty>> {
    let mut result: Vec<Vec<&ProjectedAttachedProperty>> = Vec::new();
    for property in &ir.attached_properties {
        if let Some(group) = result
            .iter_mut()
            .find(|group| group[0].statics_interface_name == property.statics_interface_name)
        {
            group.push(property);
        } else {
            result.push(vec![property]);
        }
    }
    result.sort_by(|left, right| {
        left[0]
            .statics_interface_name
            .cmp(&right[0].statics_interface_name)
    });
    result
}

fn emit_iunknown_slots(out: &mut String) {
    out.push_str(
        "    query_interface: unsafe extern \"system\" fn(*mut IUnknown, *const Guid, *mut *mut c_void) -> i32,\n\
         \x20   add_ref: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n\
         \x20   release: unsafe extern \"system\" fn(*mut IUnknown) -> u32,\n",
    );
}

fn emit_property_slots(out: &mut String, ty: &ProjectedType, property: &ProjectedProperty) {
    if property.can_read {
        out.push_str(&format!(
            "    get_{}: unsafe extern \"system\" fn(*mut {}, *mut {}) -> i32,\n",
            to_snake(&property.name),
            ty.name,
            rust_abi_type(
                &property.kind,
                property.interface_name.as_deref(),
                property.is_nullable
            )
        ));
    }
    if property.can_write {
        out.push_str(&format!(
            "    set_{}: unsafe extern \"system\" fn(*mut {}, {}) -> i32,\n",
            to_snake(&property.name),
            ty.name,
            rust_abi_type(
                &property.kind,
                property.interface_name.as_deref(),
                property.is_nullable
            )
        ));
    }
}

fn emit_property(ty: &ProjectedType, property: &ProjectedProperty) -> String {
    let mut out = String::new();
    let snake = to_snake(&property.name);
    if property.can_read {
        let abi_type = rust_abi_type(
            &property.kind,
            property.interface_name.as_deref(),
            property.is_nullable,
        );
        out.push_str(&format!(
            "    pub fn get_{snake}(&self) -> Result<{}> {{\n        unsafe {{\n            let mut value: {abi_type} = {};\n            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().get_{snake})(self.as_raw(), &mut value);\n            hresult::check(hr)?;\n            {}\n        }}\n    }}\n",
            rust_property_type(property),
            rust_abi_default(&property.kind),
            rust_property_result(property)
        ));
    }
    if property.can_write {
        let (argument_type, argument_value) = rust_property_input(property);
        let prepare = prepare_string_input(&property.kind, "value", property.is_nullable);
        out.push_str(&format!(
            "    pub fn set_{snake}(&self, value: {argument_type}) -> Result<()> {{\n{prepare}        unsafe {{\n            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().set_{snake})(self.as_raw(), {argument_value});\n            hresult::check(hr)\n        }}\n    }}\n"
        ));
    }
    let _ = ty;
    out
}

fn emit_method(_ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let snake = to_snake(&method.name);
    let rust_args = method
        .parameters
        .iter()
        .filter(|p| p.direction != "Out")
        .map(|p| format!(", {}: {}", to_snake(&p.name), rust_parameter_input_type(p)))
        .collect::<String>();
    let out_params: Vec<_> = method
        .parameters
        .iter()
        .filter(|p| p.direction == "Out")
        .collect();
    let mut body = String::new();
    for parameter in method.parameters.iter().filter(|p| p.direction != "Out") {
        body.push_str(&prepare_string_input(
            &parameter.kind,
            &to_snake(&parameter.name),
            parameter.is_nullable,
        ));
    }
    for parameter in &out_params {
        body.push_str(&format!(
            "            let mut {}: {} = {};\n",
            to_snake(&parameter.name),
            rust_abi_type(
                &parameter.kind,
                parameter.interface_name.as_deref(),
                parameter.is_nullable
            ),
            rust_abi_default(&parameter.kind)
        ));
    }
    let call_args = method
        .parameters
        .iter()
        .map(rust_parameter_call_value)
        .collect::<Vec<_>>()
        .join(", ");
    let extra = if call_args.is_empty() {
        String::new()
    } else {
        format!(", {call_args}")
    };
    body.push_str(&format!(
        "            let hr = ((*self.as_raw()).vtbl.as_ref().unwrap().{snake})(self.as_raw(){extra});\n"
    ));
    let result = if out_params.is_empty() {
        "hresult::check(hr)".to_string()
    } else {
        let values = out_params
            .iter()
            .map(|p| rust_method_out_expression(p))
            .collect::<Vec<_>>();
        let value = if values.len() == 1 {
            values[0].clone()
        } else {
            format!("({})", values.join(", "))
        };
        if out_params.iter().any(|p| p.kind == "ComInterface") {
            format!("hresult::check(hr).and_then(|_| {value})")
        } else {
            format!("hresult::check(hr).map(|_| {value})")
        }
    };
    format!(
        "    pub fn {snake}(&self{rust_args}) -> Result<{}> {{\n        unsafe {{\n{body}            {result}\n        }}\n    }}\n",
        rust_method_result_type(&out_params)
    )
}

fn rust_method_out_expression(parameter: &ProjectedParameter) -> String {
    let name = to_snake(&parameter.name);
    match parameter.kind.as_str() {
        "ComInterface" if parameter.is_nullable => {
            format!("if {name}.is_null() {{ Ok(None) }} else {{ Ok(Some(ComPtr::from_projected_raw({name})?)) }}")
        }
        "ComInterface" => format!("ComPtr::from_projected_raw({name})"),
        _ => name,
    }
}

fn vtbl_method_args(ty: &ProjectedType, method: &ProjectedMethod) -> String {
    let mut args = vec![format!("*mut {}", ty.name)];
    args.extend(method.parameters.iter().map(|p| {
        let abi = rust_abi_type(&p.kind, p.interface_name.as_deref(), p.is_nullable);
        if p.direction == "Out" {
            format!("*mut {abi}")
        } else {
            abi
        }
    }));
    args.join(", ")
}

fn lineage<'a>(ir: &'a ProjectionIr, ty: &'a ProjectedType) -> Vec<&'a ProjectedType> {
    let mut result = vec![ty];
    let mut current = ty;
    while let Some(base) = &current.base_full_name {
        current = ir
            .types
            .iter()
            .find(|candidate| &candidate.full_name == base)
            .expect("base type must be present in projection IR");
        result.push(current);
    }

    result.reverse();
    result
}

fn unique_events(ir: &ProjectionIr) -> Vec<&ProjectedEvent> {
    let mut result = Vec::new();
    for event in ir.types.iter().flat_map(|ty| ty.events.iter()) {
        if !result.iter().any(|existing: &&ProjectedEvent| {
            existing.handler_interface_name == event.handler_interface_name
        }) {
            result.push(event);
        }
    }
    result
}

fn event_handler_function(event: &ProjectedEvent) -> String {
    let name = simple_name(&event.handler_interface_name)
        .strip_prefix("IAvn")
        .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        .strip_suffix("Handler")
        .unwrap_or_else(|| {
            simple_name(&event.handler_interface_name)
                .strip_prefix("IAvn")
                .unwrap_or_else(|| simple_name(&event.handler_interface_name))
        });
    format!("{}_handler", to_snake(name))
}

fn rust_abi_type(kind: &str, interface_name: Option<&str>, is_nullable: bool) -> String {
    if let Some(geometry) = geometry::find(kind) {
        return if is_nullable {
            geometry.optional_abi_name()
        } else {
            geometry.abi_name.into()
        };
    }
    match kind {
        "CharUtf16" => "u16".into(),
        "I32" | "Bool" | "NullableBool" => "i32".into(),
        "I64" => "i64".into(),
        "TimeSpanI64" if is_nullable => "AvnOptionalTimeSpan".into(),
        "TimeSpanI64" => "i64".into(),
        "DateTimeI64" if is_nullable => "AvnOptionalDateTime".into(),
        "DateTimeI64" => "i64".into(),
        "F32" => "f32".into(),
        "F64" => "f64".into(),
        "StringUtf16" => "*mut u16".into(),
        "ComInterface" | "ComCollection" | "Brush" | "Command" | "DataTemplate" | "ItemFilter"
        | "TextFilter" | "ItemSelector" | "TextSelector" | "Notification" | "PopupPlacement"
        | "AsyncPopulator" => {
            format!(
                "*mut {}",
                simple_name(interface_name.expect("interfaceName"))
            )
        }
        "Variant" => "AvnVariant".into(),
        "PixelPointI32" => "AvnPixelPoint".into(),
        _ => "c_void".into(),
    }
}

fn rust_abi_default(kind: &str) -> &'static str {
    if geometry::is_geometry(kind) {
        return "Default::default()";
    }
    match kind {
        "F32" | "F64" => "0.0",
        "I32" | "I64" | "Bool" | "NullableBool" | "CharUtf16" | "TimeSpanI64" | "DateTimeI64" => {
            "0"
        }
        "Variant" => "AvnVariant::default()",
        "PixelPointI32" => "AvnPixelPoint::default()",
        _ => "ptr::null_mut()",
    }
}

fn rust_property_type(property: &ProjectedProperty) -> String {
    if let Some(geometry) = geometry::find(&property.kind) {
        return if property.is_nullable {
            geometry.optional_abi_name()
        } else {
            geometry.abi_name.into()
        };
    }
    match property.kind.as_str() {
        "CharUtf16" => "u16".into(),
        "I32" => "i32".into(),
        "I64" => "i64".into(),
        "TimeSpanI64" if property.is_nullable => "AvnOptionalTimeSpan".into(),
        "TimeSpanI64" => "i64".into(),
        "DateTimeI64" if property.is_nullable => "AvnOptionalDateTime".into(),
        "DateTimeI64" => "i64".into(),
        "PixelPointI32" => "AvnPixelPoint".into(),
        "F32" => "f32".into(),
        "F64" => "f64".into(),
        "Bool" => "bool".into(),
        "NullableBool" => "Option<bool>".into(),
        "StringUtf16" => "*mut u16".into(),
        "ComInterface" | "ComCollection" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            if property.is_nullable {
                format!("Option<ComPtr<{ty}>>")
            } else {
                format!("ComPtr<{ty}>")
            }
        }
        // A brush is always optional: a control with no brush reports a null pointer.
        "Brush" | "Command" | "DataTemplate" | "ItemFilter" | "TextFilter" | "ItemSelector"
        | "TextSelector" | "Notification" | "PopupPlacement" | "AsyncPopulator" => format!(
            "Option<ComPtr<{}>>",
            simple_name(property.interface_name.as_deref().expect("interfaceName"))
        ),
        "Variant" => "AvnVariant".into(),
        _ => "()".into(),
    }
}

fn rust_property_result(property: &ProjectedProperty) -> String {
    match property.kind.as_str() {
        "Bool" => "Ok(value != 0)".into(),
        "NullableBool" => {
            "match value { -1 => Ok(None), 0 => Ok(Some(false)), 1 => Ok(Some(true)), _ => Err(Error(hresult::E_INVALIDARG)) }".into()
        }
        "Variant" => "Ok(value)".into(),
        "ComInterface" if property.is_nullable => {
            "if value.is_null() { Ok(None) } else { Ok(Some(ComPtr::from_projected_raw(value)?)) }".into()
        }
        "ComCollection" if property.is_nullable => {
            "Ok(ComPtr::from_raw(value))".into()
        }
        "Brush" | "Command" | "DataTemplate" | "ItemFilter" | "TextFilter" | "ItemSelector"
        | "TextSelector" | "Notification" | "PopupPlacement" | "AsyncPopulator" => "Ok(ComPtr::from_raw(value))".into(),
        "ComInterface" => {
            "ComPtr::from_projected_raw(value)".into()
        }
        "ComCollection" => {
            "ComPtr::from_raw(value).ok_or(Error(hresult::E_POINTER))".into()
        }
        _ => "Ok(value)".into(),
    }
}

fn prepare_string_input(kind: &str, name: &str, is_nullable: bool) -> String {
    if kind != "StringUtf16" {
        return String::new();
    }
    let value = if is_nullable {
        format!("{name}.map(crate::terminated_utf16)")
    } else {
        format!("crate::terminated_utf16({name})")
    };
    format!("        let {name} = {value};\n")
}

fn rust_property_input(property: &ProjectedProperty) -> (String, String) {
    match property.kind.as_str() {
        "Bool" => ("bool".into(), "i32::from(value)".into()),
        "NullableBool" => ("Option<bool>".into(), "value.map_or(-1, i32::from)".into()),
        "StringUtf16" if property.is_nullable => (
            "Option<&[u16]>".into(),
            "value.as_ref().map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut())".into(),
        ),
        "StringUtf16" => ("&[u16]".into(), "value.as_ptr().cast_mut()".into()),
        "Variant" => ("&AvnVariant".into(), "*value".into()),
        "PixelPointI32" => ("AvnPixelPoint".into(), "value".into()),
        "ComInterface" | "ComCollection" if property.is_nullable => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (
                format!("Option<&ComPtr<{ty}>>"),
                "value.map_or(ptr::null_mut(), ComPtr::as_raw)".into(),
            )
        }
        "Brush" | "Command" | "DataTemplate" | "ItemFilter" | "TextFilter" | "ItemSelector"
        | "TextSelector" | "Notification" | "PopupPlacement" | "AsyncPopulator" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (
                format!("Option<&ComPtr<{ty}>>"),
                "value.map_or(ptr::null_mut(), ComPtr::as_raw)".into(),
            )
        }
        "ComInterface" | "ComCollection" => {
            let ty = simple_name(property.interface_name.as_deref().expect("interfaceName"));
            (format!("&ComPtr<{ty}>"), "value.as_raw()".into())
        }
        _ => (rust_property_type(property), "value".into()),
    }
}

fn rust_parameter_input_type(parameter: &ProjectedParameter) -> String {
    match parameter.kind.as_str() {
        "Bool" => "bool".into(),
        "NullableBool" => "Option<bool>".into(),
        "StringUtf16" if parameter.is_nullable => "Option<&[u16]>".into(),
        "StringUtf16" => "&[u16]".into(),
        "ComInterface" | "Notification" if parameter.is_nullable => format!(
            "Option<&ComPtr<{}>>",
            simple_name(parameter.interface_name.as_deref().expect("interfaceName"))
        ),
        "ComInterface" | "Notification" => format!(
            "&ComPtr<{}>",
            simple_name(parameter.interface_name.as_deref().expect("interfaceName"))
        ),
        _ => rust_abi_type(
            &parameter.kind,
            parameter.interface_name.as_deref(),
            parameter.is_nullable,
        ),
    }
}

fn rust_parameter_call_value(parameter: &ProjectedParameter) -> String {
    let name = to_snake(&parameter.name);
    if parameter.direction == "Out" {
        return format!("&mut {name}");
    }
    match parameter.kind.as_str() {
        "Bool" => format!("i32::from({name})"),
        "NullableBool" => format!("{name}.map_or(-1, i32::from)"),
        "StringUtf16" if parameter.is_nullable => {
            format!("{name}.as_ref().map_or(ptr::null_mut(), |v| v.as_ptr().cast_mut())")
        }
        "StringUtf16" => format!("{name}.as_ptr().cast_mut()"),
        "ComInterface" | "Notification" if parameter.is_nullable => {
            format!("{name}.map_or(ptr::null_mut(), ComPtr::as_raw)")
        }
        "ComInterface" | "Notification" => format!("{name}.as_raw()"),
        _ => name,
    }
}

fn rust_method_result_type(parameters: &[&ProjectedParameter]) -> String {
    fn result_type(parameter: &ProjectedParameter) -> String {
        if parameter.kind == "ComInterface" {
            let ty = simple_name(parameter.interface_name.as_deref().expect("interfaceName"));
            return if parameter.is_nullable {
                format!("Option<ComPtr<{ty}>>")
            } else {
                format!("ComPtr<{ty}>")
            };
        }
        rust_abi_type(
            &parameter.kind,
            parameter.interface_name.as_deref(),
            parameter.is_nullable,
        )
    }
    match parameters.len() {
        0 => "()".into(),
        1 => result_type(parameters[0]),
        _ => format!(
            "({})",
            parameters
                .iter()
                .map(|p| result_type(p))
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn guid_literal(iid: &str) -> String {
    let parts: Vec<&str> = iid.split('-').collect();
    if parts.len() != 5 {
        return "Guid::IUNKNOWN".into();
    }
    let d4 = parts[3].to_string() + parts[4];
    let bytes: Vec<String> = (0..8)
        .map(|i| format!("0x{}", &d4[i * 2..i * 2 + 2]))
        .collect();
    format!(
        "Guid {{ data1: 0x{}, data2: 0x{}, data3: 0x{}, data4: [{}] }}",
        parts[0],
        parts[1],
        parts[2],
        bytes.join(", ")
    )
}

fn interface_suffix(name: &str) -> &str {
    name.strip_prefix("IAvn").unwrap_or(name)
}

fn simple_name(full_name: &str) -> &str {
    full_name.rsplit('.').next().unwrap_or(full_name)
}

fn to_snake(name: &str) -> String {
    let mut out = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index > 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

fn to_shouty(name: &str) -> String {
    to_snake(name).to_uppercase()
}
